/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AzureAppServiceListerExpansion allows custom methods to be added to
// AzureAppServiceLister.
type AzureAppServiceListerExpansion interface{}

// AzureAppServiceNamespaceListerExpansion allows custom methods to be added to
// AzureAppServiceNamespaceLister.
type AzureAppServiceNamespaceListerExpansion interface{}

// AzureFnAppListerExpansion allows custom methods to be added to
// AzureFnAppLister.
type AzureFnAppListerExpansion interface{}

// AzureFnAppNamespaceListerExpansion allows custom methods to be added to
// AzureFnAppNamespaceLister.
type AzureFnAppNamespaceListerExpansion interface{}

// F4dpAzFnv1ListerExpansion allows custom methods to be added to
// F4dpAzFnv1Lister.
type F4dpAzFnv1ListerExpansion interface{}

// F4dpAzFnv1NamespaceListerExpansion allows custom methods to be added to
// F4dpAzFnv1NamespaceLister.
type F4dpAzFnv1NamespaceListerExpansion interface{}

// F4dpAzSqlListerExpansion allows custom methods to be added to
// F4dpAzSqlLister.
type F4dpAzSqlListerExpansion interface{}

// F4dpAzSqlNamespaceListerExpansion allows custom methods to be added to
// F4dpAzSqlNamespaceLister.
type F4dpAzSqlNamespaceListerExpansion interface{}

// F4dpAzStgv1ListerExpansion allows custom methods to be added to
// F4dpAzStgv1Lister.
type F4dpAzStgv1ListerExpansion interface{}

// F4dpAzStgv1NamespaceListerExpansion allows custom methods to be added to
// F4dpAzStgv1NamespaceLister.
type F4dpAzStgv1NamespaceListerExpansion interface{}
