/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AzureAppServiceListerExpansion allows custom methods to be added to
// AzureAppServiceLister.
type AzureAppServiceListerExpansion interface{}

// AzureAppServiceNamespaceListerExpansion allows custom methods to be added to
// AzureAppServiceNamespaceLister.
type AzureAppServiceNamespaceListerExpansion interface{}

// AzureFnAppListerExpansion allows custom methods to be added to
// AzureFnAppLister.
type AzureFnAppListerExpansion interface{}

// AzureFnAppNamespaceListerExpansion allows custom methods to be added to
// AzureFnAppNamespaceLister.
type AzureFnAppNamespaceListerExpansion interface{}

// F4dpAzFnv1ListerExpansion allows custom methods to be added to
// F4dpAzFnv1Lister.
type F4dpAzFnv1ListerExpansion interface{}

// F4dpAzFnv1NamespaceListerExpansion allows custom methods to be added to
// F4dpAzFnv1NamespaceLister.
type F4dpAzFnv1NamespaceListerExpansion interface{}

// F4dpAzSqlListerExpansion allows custom methods to be added to
// F4dpAzSqlLister.
type F4dpAzSqlListerExpansion interface{}

// F4dpAzSqlNamespaceListerExpansion allows custom methods to be added to
// F4dpAzSqlNamespaceLister.
type F4dpAzSqlNamespaceListerExpansion interface{}

// F4dpAzStgv1ListerExpansion allows custom methods to be added to
// F4dpAzStgv1Lister.
type F4dpAzStgv1ListerExpansion interface{}

// F4dpAzStgv1NamespaceListerExpansion allows custom methods to be added to
// F4dpAzStgv1NamespaceLister.
type F4dpAzStgv1NamespaceListerExpansion interface{}

// SDPAzADLSv1ListerExpansion allows custom methods to be added to
// SDPAzADLSv1Lister.
type SDPAzADLSv1ListerExpansion interface{}

// SDPAzADLSv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzADLSv1NamespaceLister.
type SDPAzADLSv1NamespaceListerExpansion interface{}

// SDPAzAppv1ListerExpansion allows custom methods to be added to
// SDPAzAppv1Lister.
type SDPAzAppv1ListerExpansion interface{}

// SDPAzAppv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzAppv1NamespaceLister.
type SDPAzAppv1NamespaceListerExpansion interface{}

// SDPAzFnv1ListerExpansion allows custom methods to be added to
// SDPAzFnv1Lister.
type SDPAzFnv1ListerExpansion interface{}

// SDPAzFnv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzFnv1NamespaceLister.
type SDPAzFnv1NamespaceListerExpansion interface{}

// SDPAzFnv2ListerExpansion allows custom methods to be added to
// SDPAzFnv2Lister.
type SDPAzFnv2ListerExpansion interface{}

// SDPAzFnv2NamespaceListerExpansion allows custom methods to be added to
// SDPAzFnv2NamespaceLister.
type SDPAzFnv2NamespaceListerExpansion interface{}

// SDPAzSqlv1ListerExpansion allows custom methods to be added to
// SDPAzSqlv1Lister.
type SDPAzSqlv1ListerExpansion interface{}

// SDPAzSqlv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzSqlv1NamespaceLister.
type SDPAzSqlv1NamespaceListerExpansion interface{}

// SDPAzStgv1ListerExpansion allows custom methods to be added to
// SDPAzStgv1Lister.
type SDPAzStgv1ListerExpansion interface{}

// SDPAzStgv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzStgv1NamespaceLister.
type SDPAzStgv1NamespaceListerExpansion interface{}

// SDPAzadfv1ListerExpansion allows custom methods to be added to
// SDPAzadfv1Lister.
type SDPAzadfv1ListerExpansion interface{}

// SDPAzadfv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzadfv1NamespaceLister.
type SDPAzadfv1NamespaceListerExpansion interface{}

// SDPAzappserviceplanv1ListerExpansion allows custom methods to be added to
// SDPAzappserviceplanv1Lister.
type SDPAzappserviceplanv1ListerExpansion interface{}

// SDPAzappserviceplanv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzappserviceplanv1NamespaceLister.
type SDPAzappserviceplanv1NamespaceListerExpansion interface{}

// SDPAzdbv1ListerExpansion allows custom methods to be added to
// SDPAzdbv1Lister.
type SDPAzdbv1ListerExpansion interface{}

// SDPAzdbv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzdbv1NamespaceLister.
type SDPAzdbv1NamespaceListerExpansion interface{}

// SDPAzplatformeventsv1ListerExpansion allows custom methods to be added to
// SDPAzplatformeventsv1Lister.
type SDPAzplatformeventsv1ListerExpansion interface{}

// SDPAzplatformeventsv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzplatformeventsv1NamespaceLister.
type SDPAzplatformeventsv1NamespaceListerExpansion interface{}

// SDPAzsbv1ListerExpansion allows custom methods to be added to
// SDPAzsbv1Lister.
type SDPAzsbv1ListerExpansion interface{}

// SDPAzsbv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzsbv1NamespaceLister.
type SDPAzsbv1NamespaceListerExpansion interface{}

// StratosAzStgv1ListerExpansion allows custom methods to be added to
// StratosAzStgv1Lister.
type StratosAzStgv1ListerExpansion interface{}

// StratosAzStgv1NamespaceListerExpansion allows custom methods to be added to
// StratosAzStgv1NamespaceLister.
type StratosAzStgv1NamespaceListerExpansion interface{}
