/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/modules/v1alpha1"
)

// FakeSDPAzFnv2s implements SDPAzFnv2Interface
type FakeSDPAzFnv2s struct {
	Fake *FakeModulesV1alpha1
	ns   string
}

var sdpazfnv2sResource = schema.GroupVersionResource{Group: "modules.kubeform.com", Version: "v1alpha1", Resource: "sdpazfnv2s"}

var sdpazfnv2sKind = schema.GroupVersionKind{Group: "modules.kubeform.com", Version: "v1alpha1", Kind: "SDPAzFnv2"}

// Get takes name of the sDPAzFnv2, and returns the corresponding sDPAzFnv2 object, and an error if there is any.
func (c *FakeSDPAzFnv2s) Get(name string, options v1.GetOptions) (result *v1alpha1.SDPAzFnv2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sdpazfnv2sResource, c.ns, name), &v1alpha1.SDPAzFnv2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzFnv2), err
}

// List takes label and field selectors, and returns the list of SDPAzFnv2s that match those selectors.
func (c *FakeSDPAzFnv2s) List(opts v1.ListOptions) (result *v1alpha1.SDPAzFnv2List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sdpazfnv2sResource, sdpazfnv2sKind, c.ns, opts), &v1alpha1.SDPAzFnv2List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SDPAzFnv2List{ListMeta: obj.(*v1alpha1.SDPAzFnv2List).ListMeta}
	for _, item := range obj.(*v1alpha1.SDPAzFnv2List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sDPAzFnv2s.
func (c *FakeSDPAzFnv2s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sdpazfnv2sResource, c.ns, opts))

}

// Create takes the representation of a sDPAzFnv2 and creates it.  Returns the server's representation of the sDPAzFnv2, and an error, if there is any.
func (c *FakeSDPAzFnv2s) Create(sDPAzFnv2 *v1alpha1.SDPAzFnv2) (result *v1alpha1.SDPAzFnv2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sdpazfnv2sResource, c.ns, sDPAzFnv2), &v1alpha1.SDPAzFnv2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzFnv2), err
}

// Update takes the representation of a sDPAzFnv2 and updates it. Returns the server's representation of the sDPAzFnv2, and an error, if there is any.
func (c *FakeSDPAzFnv2s) Update(sDPAzFnv2 *v1alpha1.SDPAzFnv2) (result *v1alpha1.SDPAzFnv2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sdpazfnv2sResource, c.ns, sDPAzFnv2), &v1alpha1.SDPAzFnv2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzFnv2), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSDPAzFnv2s) UpdateStatus(sDPAzFnv2 *v1alpha1.SDPAzFnv2) (*v1alpha1.SDPAzFnv2, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sdpazfnv2sResource, "status", c.ns, sDPAzFnv2), &v1alpha1.SDPAzFnv2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzFnv2), err
}

// Delete takes name of the sDPAzFnv2 and deletes it. Returns an error if one occurs.
func (c *FakeSDPAzFnv2s) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sdpazfnv2sResource, c.ns, name), &v1alpha1.SDPAzFnv2{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSDPAzFnv2s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sdpazfnv2sResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SDPAzFnv2List{})
	return err
}

// Patch applies the patch and returns the patched sDPAzFnv2.
func (c *FakeSDPAzFnv2s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SDPAzFnv2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sdpazfnv2sResource, c.ns, name, pt, data, subresources...), &v1alpha1.SDPAzFnv2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzFnv2), err
}
