/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/modules/v1alpha1"
)

// FakeSDPAzadfv1s implements SDPAzadfv1Interface
type FakeSDPAzadfv1s struct {
	Fake *FakeModulesV1alpha1
	ns   string
}

var sdpazadfv1sResource = schema.GroupVersionResource{Group: "modules.kubeform.com", Version: "v1alpha1", Resource: "sdpazadfv1s"}

var sdpazadfv1sKind = schema.GroupVersionKind{Group: "modules.kubeform.com", Version: "v1alpha1", Kind: "SDPAzadfv1"}

// Get takes name of the sDPAzadfv1, and returns the corresponding sDPAzadfv1 object, and an error if there is any.
func (c *FakeSDPAzadfv1s) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SDPAzadfv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sdpazadfv1sResource, c.ns, name), &v1alpha1.SDPAzadfv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzadfv1), err
}

// List takes label and field selectors, and returns the list of SDPAzadfv1s that match those selectors.
func (c *FakeSDPAzadfv1s) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SDPAzadfv1List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sdpazadfv1sResource, sdpazadfv1sKind, c.ns, opts), &v1alpha1.SDPAzadfv1List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SDPAzadfv1List{ListMeta: obj.(*v1alpha1.SDPAzadfv1List).ListMeta}
	for _, item := range obj.(*v1alpha1.SDPAzadfv1List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sDPAzadfv1s.
func (c *FakeSDPAzadfv1s) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sdpazadfv1sResource, c.ns, opts))

}

// Create takes the representation of a sDPAzadfv1 and creates it.  Returns the server's representation of the sDPAzadfv1, and an error, if there is any.
func (c *FakeSDPAzadfv1s) Create(ctx context.Context, sDPAzadfv1 *v1alpha1.SDPAzadfv1, opts v1.CreateOptions) (result *v1alpha1.SDPAzadfv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sdpazadfv1sResource, c.ns, sDPAzadfv1), &v1alpha1.SDPAzadfv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzadfv1), err
}

// Update takes the representation of a sDPAzadfv1 and updates it. Returns the server's representation of the sDPAzadfv1, and an error, if there is any.
func (c *FakeSDPAzadfv1s) Update(ctx context.Context, sDPAzadfv1 *v1alpha1.SDPAzadfv1, opts v1.UpdateOptions) (result *v1alpha1.SDPAzadfv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sdpazadfv1sResource, c.ns, sDPAzadfv1), &v1alpha1.SDPAzadfv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzadfv1), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSDPAzadfv1s) UpdateStatus(ctx context.Context, sDPAzadfv1 *v1alpha1.SDPAzadfv1, opts v1.UpdateOptions) (*v1alpha1.SDPAzadfv1, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sdpazadfv1sResource, "status", c.ns, sDPAzadfv1), &v1alpha1.SDPAzadfv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzadfv1), err
}

// Delete takes name of the sDPAzadfv1 and deletes it. Returns an error if one occurs.
func (c *FakeSDPAzadfv1s) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sdpazadfv1sResource, c.ns, name), &v1alpha1.SDPAzadfv1{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSDPAzadfv1s) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sdpazadfv1sResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SDPAzadfv1List{})
	return err
}

// Patch applies the patch and returns the patched sDPAzadfv1.
func (c *FakeSDPAzadfv1s) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SDPAzadfv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sdpazadfv1sResource, c.ns, name, pt, data, subresources...), &v1alpha1.SDPAzadfv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzadfv1), err
}
