/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/modules/v1alpha1"
)

// FakeF4dpAzFnv1s implements F4dpAzFnv1Interface
type FakeF4dpAzFnv1s struct {
	Fake *FakeModulesV1alpha1
	ns   string
}

var f4dpazfnv1sResource = schema.GroupVersionResource{Group: "modules.kubeform.com", Version: "v1alpha1", Resource: "f4dpazfnv1s"}

var f4dpazfnv1sKind = schema.GroupVersionKind{Group: "modules.kubeform.com", Version: "v1alpha1", Kind: "F4dpAzFnv1"}

// Get takes name of the f4dpAzFnv1, and returns the corresponding f4dpAzFnv1 object, and an error if there is any.
func (c *FakeF4dpAzFnv1s) Get(name string, options v1.GetOptions) (result *v1alpha1.F4dpAzFnv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(f4dpazfnv1sResource, c.ns, name), &v1alpha1.F4dpAzFnv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.F4dpAzFnv1), err
}

// List takes label and field selectors, and returns the list of F4dpAzFnv1s that match those selectors.
func (c *FakeF4dpAzFnv1s) List(opts v1.ListOptions) (result *v1alpha1.F4dpAzFnv1List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(f4dpazfnv1sResource, f4dpazfnv1sKind, c.ns, opts), &v1alpha1.F4dpAzFnv1List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.F4dpAzFnv1List{ListMeta: obj.(*v1alpha1.F4dpAzFnv1List).ListMeta}
	for _, item := range obj.(*v1alpha1.F4dpAzFnv1List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested f4dpAzFnv1s.
func (c *FakeF4dpAzFnv1s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(f4dpazfnv1sResource, c.ns, opts))

}

// Create takes the representation of a f4dpAzFnv1 and creates it.  Returns the server's representation of the f4dpAzFnv1, and an error, if there is any.
func (c *FakeF4dpAzFnv1s) Create(f4dpAzFnv1 *v1alpha1.F4dpAzFnv1) (result *v1alpha1.F4dpAzFnv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(f4dpazfnv1sResource, c.ns, f4dpAzFnv1), &v1alpha1.F4dpAzFnv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.F4dpAzFnv1), err
}

// Update takes the representation of a f4dpAzFnv1 and updates it. Returns the server's representation of the f4dpAzFnv1, and an error, if there is any.
func (c *FakeF4dpAzFnv1s) Update(f4dpAzFnv1 *v1alpha1.F4dpAzFnv1) (result *v1alpha1.F4dpAzFnv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(f4dpazfnv1sResource, c.ns, f4dpAzFnv1), &v1alpha1.F4dpAzFnv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.F4dpAzFnv1), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeF4dpAzFnv1s) UpdateStatus(f4dpAzFnv1 *v1alpha1.F4dpAzFnv1) (*v1alpha1.F4dpAzFnv1, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(f4dpazfnv1sResource, "status", c.ns, f4dpAzFnv1), &v1alpha1.F4dpAzFnv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.F4dpAzFnv1), err
}

// Delete takes name of the f4dpAzFnv1 and deletes it. Returns an error if one occurs.
func (c *FakeF4dpAzFnv1s) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(f4dpazfnv1sResource, c.ns, name), &v1alpha1.F4dpAzFnv1{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeF4dpAzFnv1s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(f4dpazfnv1sResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.F4dpAzFnv1List{})
	return err
}

// Patch applies the patch and returns the patched f4dpAzFnv1.
func (c *FakeF4dpAzFnv1s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.F4dpAzFnv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(f4dpazfnv1sResource, c.ns, name, pt, data, subresources...), &v1alpha1.F4dpAzFnv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.F4dpAzFnv1), err
}
