/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/modules/v1alpha1"
)

// FakeSDPAzADLSv1s implements SDPAzADLSv1Interface
type FakeSDPAzADLSv1s struct {
	Fake *FakeModulesV1alpha1
	ns   string
}

var sdpazadlsv1sResource = schema.GroupVersionResource{Group: "modules.kubeform.com", Version: "v1alpha1", Resource: "sdpazadlsv1s"}

var sdpazadlsv1sKind = schema.GroupVersionKind{Group: "modules.kubeform.com", Version: "v1alpha1", Kind: "SDPAzADLSv1"}

// Get takes name of the sDPAzADLSv1, and returns the corresponding sDPAzADLSv1 object, and an error if there is any.
func (c *FakeSDPAzADLSv1s) Get(name string, options v1.GetOptions) (result *v1alpha1.SDPAzADLSv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sdpazadlsv1sResource, c.ns, name), &v1alpha1.SDPAzADLSv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzADLSv1), err
}

// List takes label and field selectors, and returns the list of SDPAzADLSv1s that match those selectors.
func (c *FakeSDPAzADLSv1s) List(opts v1.ListOptions) (result *v1alpha1.SDPAzADLSv1List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sdpazadlsv1sResource, sdpazadlsv1sKind, c.ns, opts), &v1alpha1.SDPAzADLSv1List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SDPAzADLSv1List{ListMeta: obj.(*v1alpha1.SDPAzADLSv1List).ListMeta}
	for _, item := range obj.(*v1alpha1.SDPAzADLSv1List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sDPAzADLSv1s.
func (c *FakeSDPAzADLSv1s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sdpazadlsv1sResource, c.ns, opts))

}

// Create takes the representation of a sDPAzADLSv1 and creates it.  Returns the server's representation of the sDPAzADLSv1, and an error, if there is any.
func (c *FakeSDPAzADLSv1s) Create(sDPAzADLSv1 *v1alpha1.SDPAzADLSv1) (result *v1alpha1.SDPAzADLSv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sdpazadlsv1sResource, c.ns, sDPAzADLSv1), &v1alpha1.SDPAzADLSv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzADLSv1), err
}

// Update takes the representation of a sDPAzADLSv1 and updates it. Returns the server's representation of the sDPAzADLSv1, and an error, if there is any.
func (c *FakeSDPAzADLSv1s) Update(sDPAzADLSv1 *v1alpha1.SDPAzADLSv1) (result *v1alpha1.SDPAzADLSv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sdpazadlsv1sResource, c.ns, sDPAzADLSv1), &v1alpha1.SDPAzADLSv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzADLSv1), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSDPAzADLSv1s) UpdateStatus(sDPAzADLSv1 *v1alpha1.SDPAzADLSv1) (*v1alpha1.SDPAzADLSv1, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sdpazadlsv1sResource, "status", c.ns, sDPAzADLSv1), &v1alpha1.SDPAzADLSv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzADLSv1), err
}

// Delete takes name of the sDPAzADLSv1 and deletes it. Returns an error if one occurs.
func (c *FakeSDPAzADLSv1s) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sdpazadlsv1sResource, c.ns, name), &v1alpha1.SDPAzADLSv1{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSDPAzADLSv1s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sdpazadlsv1sResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SDPAzADLSv1List{})
	return err
}

// Patch applies the patch and returns the patched sDPAzADLSv1.
func (c *FakeSDPAzADLSv1s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SDPAzADLSv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sdpazadlsv1sResource, c.ns, name, pt, data, subresources...), &v1alpha1.SDPAzADLSv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SDPAzADLSv1), err
}
