/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "kubeform.dev/kubeform/apis/modules/v1alpha2"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSDPAzAppv1s implements SDPAzAppv1Interface
type FakeSDPAzAppv1s struct {
	Fake *FakeModulesV1alpha2
	ns   string
}

var sdpazappv1sResource = schema.GroupVersionResource{Group: "modules.kubeform.com", Version: "v1alpha2", Resource: "sdpazappv1s"}

var sdpazappv1sKind = schema.GroupVersionKind{Group: "modules.kubeform.com", Version: "v1alpha2", Kind: "SDPAzAppv1"}

// Get takes name of the sDPAzAppv1, and returns the corresponding sDPAzAppv1 object, and an error if there is any.
func (c *FakeSDPAzAppv1s) Get(name string, options v1.GetOptions) (result *v1alpha2.SDPAzAppv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sdpazappv1sResource, c.ns, name), &v1alpha2.SDPAzAppv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.SDPAzAppv1), err
}

// List takes label and field selectors, and returns the list of SDPAzAppv1s that match those selectors.
func (c *FakeSDPAzAppv1s) List(opts v1.ListOptions) (result *v1alpha2.SDPAzAppv1List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sdpazappv1sResource, sdpazappv1sKind, c.ns, opts), &v1alpha2.SDPAzAppv1List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.SDPAzAppv1List{ListMeta: obj.(*v1alpha2.SDPAzAppv1List).ListMeta}
	for _, item := range obj.(*v1alpha2.SDPAzAppv1List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sDPAzAppv1s.
func (c *FakeSDPAzAppv1s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sdpazappv1sResource, c.ns, opts))

}

// Create takes the representation of a sDPAzAppv1 and creates it.  Returns the server's representation of the sDPAzAppv1, and an error, if there is any.
func (c *FakeSDPAzAppv1s) Create(sDPAzAppv1 *v1alpha2.SDPAzAppv1) (result *v1alpha2.SDPAzAppv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sdpazappv1sResource, c.ns, sDPAzAppv1), &v1alpha2.SDPAzAppv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.SDPAzAppv1), err
}

// Update takes the representation of a sDPAzAppv1 and updates it. Returns the server's representation of the sDPAzAppv1, and an error, if there is any.
func (c *FakeSDPAzAppv1s) Update(sDPAzAppv1 *v1alpha2.SDPAzAppv1) (result *v1alpha2.SDPAzAppv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sdpazappv1sResource, c.ns, sDPAzAppv1), &v1alpha2.SDPAzAppv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.SDPAzAppv1), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSDPAzAppv1s) UpdateStatus(sDPAzAppv1 *v1alpha2.SDPAzAppv1) (*v1alpha2.SDPAzAppv1, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sdpazappv1sResource, "status", c.ns, sDPAzAppv1), &v1alpha2.SDPAzAppv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.SDPAzAppv1), err
}

// Delete takes name of the sDPAzAppv1 and deletes it. Returns an error if one occurs.
func (c *FakeSDPAzAppv1s) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sdpazappv1sResource, c.ns, name), &v1alpha2.SDPAzAppv1{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSDPAzAppv1s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sdpazappv1sResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.SDPAzAppv1List{})
	return err
}

// Patch applies the patch and returns the patched sDPAzAppv1.
func (c *FakeSDPAzAppv1s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.SDPAzAppv1, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sdpazappv1sResource, c.ns, name, pt, data, subresources...), &v1alpha2.SDPAzAppv1{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.SDPAzAppv1), err
}
