trigger:
  branches:
    include:
    - feature/tn-merging-upstream

variables:
  system.debug: true

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: stratos
    ref: refs/heads/feature/tn-installing-aks-test
    type: github
    endpoint: 'Sede-X Github (ThomasNal)'
    # endpoint: 'Sede-x Github'
    name: sede-x/stratos-core-bootstrap

stages:
- stage: DeployStaging
  jobs:
  - job: Deploy
    steps:
    - checkout: stratos
      persistCredentials: true
    - script: |
        git checkout feature/tn-installing-aks-test
        echo "Hello World!" > staging/AKS-Test/.hello-world
        git config --global user.email "sedp-ci@shell.com"
        git config --global user.name "Azure Pipelines"
        git add  staging/AKS-Test/.hello-world
        git commit -m "[kubeform-dbg] Add .hello-world"
        git push
    - script: |
        git rm staging/AKS-Test/.hello-world
        git commit -m "[kubeform-dbg] Remove .hello-world"
        git push
