trigger:
  branches:
    include:
    - feature/tn-merging-upstream

variables:
  system.debug: true

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: stratos
    ref: refs/feature/tn-installing-aks-test
    type: github
    endpoint: 'Sede-X Github (ThomasNal)'
    name: sede-x/stratos-core-bootstrap

#   - repository: stratos
#     type: github
#     endpoint: 'Sede-x Github'
#     name: sede-x/stratos-core-bootstrap

stages:
- stage: DeployStaging
  jobs:
  - job: Deploy
    steps:
    - checkout: stratos
      persistCredentials: true
    - script: |
        git checkout feature/tn-installing-aks-test
        echo "my change" > staging/AKS-Test/.dbg
        git config --global user.email "sedp-ci@shell.com"
        git config --global user.name "Azure Pipelines"
        git add  staging/AKS-Test/.dbg
        git commit -m "[kubeform-dbg] Commit msg"
        git push
