trigger:
  branches:
    include:
    - feature/tn-merging-upstream

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: stratos
    type: github
    endpoint: 'Sede-x Github'
    name: sede-x/stratos-core-bootstrap

stages:
- stage: DeployStaging
  jobs:
  - deployment: Deploy
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: Checkout kubeform
          - checkout: stratos
            displayName: Checkout stratos
            persistCredentials: true
          - script: git checkout feature/tn-installing-aks-test
            displayName: Checkout stratos branch
            workingDirectory: stratos-core-bootstrap

          - script: |
              git config --global user.email "sedp-ci@shell.com"
              git config --global user.name "Azure Pipelines"
            displayName: Set git properties

          - script: |
              echo "my change" > staging/AKS-Test/.dbg
              git add  staging/AKS-Test/.dbg
              git commit -m "[kubeform-dbg] Update crd-conversion config"
              git push
            displayName: Push updates to crd-conversion config
            workingDirectory: stratos-core-bootstrap
