trigger:
  branches:
    include:
    - '*'
    exclude:
    - master
  paths:
    include:
    - module-sources.json

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: GO111MODULE
  value: on
- name: CGO_ENABLED
  value: '0'
- name: GOROOT
  value: '/opt/hostedtoolcache/go/1.12.12/x64'
- name: GOPRIVATE
  value: 'dev.azure.com/sede-ds-adp'
- group: gogit


resources:
  repositories:
  - repository: kfc
    type: git
    name: Platform - General/kfc

steps:
- checkout: self
  displayName: Checkout kubeform
  persistCredentials: true
- checkout: kfc
  displayName: Checkout kfc
  persistCredentials: true
- task: GoTool@0
  inputs:
    version: '1.12.12'
- script: |
    git config --global user.email "sedp-ci@shell.com"
    git config --global user.name "Azure Pipeline"
    git config --global url."https://test:${GIT_READ_TOKEN}@dev.azure.com/sede-ds-adp/Platform%20-%20General/_git/kubeform".insteadOf https://dev.azure.com/sede-ds-adp/kubeform
  displayName: Set git properties
- script: make build
  displayName: Build kubeform binaries
  workingDirectory: kubeform
- script: make gen
  displayName: Run kubeform codegen
  workingDirectory: kubeform
- script: |
    git add -A
    git commit -m "[skip-ci] Update Terraform modules"
    git push origin HEAD:${BUILD_SOURCEBRANCH/#refs\/heads\/}
  displayName: Commit & push results to kubeform
  workingDirectory: kubeform
- script: git rev-parse HEAD > ../kubeform-sha
  displayName: Store kubeform revision for kfc to use
  workingDirectory: kubeform
- script: go mod edit -replace "kubeform.dev/kubeform=dev.azure.com/sede-ds-adp/kubeform.git@$(cat ../kubeform-sha)"
  displayName: Point kfc to the right revision of kubeform
  workingDirectory: kfc
- script: go mod tidy && go mod vendor
  displayName: Update vendored version of kubeform in kfc
  workingDirectory: kfc
- script: |
    git add -A
    git commit -m "[auto] Update Terraform modules"
    git push -f origin HEAD:${BUILD_SOURCEBRANCH}
  displayName: Commit & push changes to kfc
  workingDirectory: kfc
- script: make build
  displayName: Build kfc binaries
  workingDirectory: kfc
- script: make container
  displayName: Build kfc containers
  workingDirectory: kfc
- script: make push
  displayName: Push kfc containers
  workingDirectory: kfc
