trigger:
  branches:
    include:
    - feature/tn-merging-upstream

variables:
  system.debug: true

pool:
  vmImage: 'ubuntu-latest'

# resources:
#   repositories:
#   - repository: stratos
#     type: github
#     endpoint: 'Sede-x Github'
#     name: sede-x/stratos-core-bootstrap

stages:
- stage: DeployStaging
  variables:
    - group: KUBEFORM_DBG
  jobs:
  - job: Deploy
    steps:
    - script: |
        git clone https://$PAT@github.com/sede-x/stratos-core-bootstrap.git
        cd stratos-core-bootstrap
        git checkout feature/tn-installing-aks-test
        echo "my change" > staging/AKS-Test/.dbg
        git config --global user.email "sedp-ci@shell.com"
        git config --global user.name "Azure Pipelines"
        git add  staging/AKS-Test/.dbg
        git commit -m "[kubeform-dbg] Commit msg"
        git push -f origin HEAD:feature/tn-installing-aks-test
      env:
        PAT: $(THOMASNAL_PAT)
