/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// SDPAzAppv1ListerExpansion allows custom methods to be added to
// SDPAzAppv1Lister.
type SDPAzAppv1ListerExpansion interface{}

// SDPAzAppv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzAppv1NamespaceLister.
type SDPAzAppv1NamespaceListerExpansion interface{}

// SDPAzFnv1ListerExpansion allows custom methods to be added to
// SDPAzFnv1Lister.
type SDPAzFnv1ListerExpansion interface{}

// SDPAzFnv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzFnv1NamespaceLister.
type SDPAzFnv1NamespaceListerExpansion interface{}

// SDPAzSqlv1ListerExpansion allows custom methods to be added to
// SDPAzSqlv1Lister.
type SDPAzSqlv1ListerExpansion interface{}

// SDPAzSqlv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzSqlv1NamespaceLister.
type SDPAzSqlv1NamespaceListerExpansion interface{}

// SDPAzadfv1ListerExpansion allows custom methods to be added to
// SDPAzadfv1Lister.
type SDPAzadfv1ListerExpansion interface{}

// SDPAzadfv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzadfv1NamespaceLister.
type SDPAzadfv1NamespaceListerExpansion interface{}

// SDPAzsbv1ListerExpansion allows custom methods to be added to
// SDPAzsbv1Lister.
type SDPAzsbv1ListerExpansion interface{}

// SDPAzsbv1NamespaceListerExpansion allows custom methods to be added to
// SDPAzsbv1NamespaceLister.
type SDPAzsbv1NamespaceListerExpansion interface{}

// StratosAzStgv1ListerExpansion allows custom methods to be added to
// StratosAzStgv1Lister.
type StratosAzStgv1ListerExpansion interface{}

// StratosAzStgv1NamespaceListerExpansion allows custom methods to be added to
// StratosAzStgv1NamespaceLister.
type StratosAzStgv1NamespaceListerExpansion interface{}

// ThomasStorageAccountListerExpansion allows custom methods to be added to
// ThomasStorageAccountLister.
type ThomasStorageAccountListerExpansion interface{}

// ThomasStorageAccountNamespaceListerExpansion allows custom methods to be added to
// ThomasStorageAccountNamespaceLister.
type ThomasStorageAccountNamespaceListerExpansion interface{}
