/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha2

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha2"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type CdnEndpoint struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CdnEndpointSpec   `json:"spec,omitempty"`
	Status            CdnEndpointStatus `json:"status,omitempty"`
}

type CdnEndpointSpecDeliveryRuleCacheExpirationAction struct {
	Behavior string `json:"behavior" tf:"behavior"`
	// +optional
	Duration string `json:"duration,omitempty" tf:"duration,omitempty"`
}

type CdnEndpointSpecDeliveryRuleCacheKeyQueryStringAction struct {
	Behavior string `json:"behavior" tf:"behavior"`
	// +optional
	Parameters string `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

type CdnEndpointSpecDeliveryRuleCookiesCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	Selector        string `json:"selector" tf:"selector"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleDeviceCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	// +optional
	Operator string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type CdnEndpointSpecDeliveryRuleHttpVersionCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	// +optional
	Operator string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type CdnEndpointSpecDeliveryRuleModifyRequestHeaderAction struct {
	Action string `json:"action" tf:"action"`
	Name   string `json:"name" tf:"name"`
	// +optional
	Value string `json:"value,omitempty" tf:"value,omitempty"`
}

type CdnEndpointSpecDeliveryRuleModifyResponseHeaderAction struct {
	Action string `json:"action" tf:"action"`
	Name   string `json:"name" tf:"name"`
	// +optional
	Value string `json:"value,omitempty" tf:"value,omitempty"`
}

type CdnEndpointSpecDeliveryRulePostArgCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	Selector        string `json:"selector" tf:"selector"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleQueryStringCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleRemoteAddressCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
}

type CdnEndpointSpecDeliveryRuleRequestBodyCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleRequestHeaderCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	Selector        string `json:"selector" tf:"selector"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleRequestMethodCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	// +optional
	Operator string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type CdnEndpointSpecDeliveryRuleRequestSchemeCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	// +optional
	Operator string `json:"operator,omitempty" tf:"operator,omitempty"`
}

type CdnEndpointSpecDeliveryRuleRequestURICondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleUrlFileExtensionCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleUrlFileNameCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleUrlPathCondition struct {
	// +kubebuilder:validation:MinItems=1
	MatchValues []string `json:"matchValues" tf:"match_values"`
	// +optional
	NegateCondition bool   `json:"negateCondition,omitempty" tf:"negate_condition,omitempty"`
	Operator        string `json:"operator" tf:"operator"`
	// +optional
	Transforms []string `json:"transforms,omitempty" tf:"transforms,omitempty"`
}

type CdnEndpointSpecDeliveryRuleUrlRedirectAction struct {
	// +optional
	Fragment string `json:"fragment,omitempty" tf:"fragment,omitempty"`
	// +optional
	Hostname string `json:"hostname,omitempty" tf:"hostname,omitempty"`
	// +optional
	Path string `json:"path,omitempty" tf:"path,omitempty"`
	// +optional
	Protocol string `json:"protocol,omitempty" tf:"protocol,omitempty"`
	// +optional
	QueryString  string `json:"queryString,omitempty" tf:"query_string,omitempty"`
	RedirectType string `json:"redirectType" tf:"redirect_type"`
}

type CdnEndpointSpecDeliveryRuleUrlRewriteAction struct {
	Destination string `json:"destination" tf:"destination"`
	// +optional
	PreserveUnmatchedPath bool   `json:"preserveUnmatchedPath,omitempty" tf:"preserve_unmatched_path,omitempty"`
	SourcePattern         string `json:"sourcePattern" tf:"source_pattern"`
}

type CdnEndpointSpecDeliveryRule struct {
	// +optional
	// +kubebuilder:validation:MaxItems=1
	CacheExpirationAction []CdnEndpointSpecDeliveryRuleCacheExpirationAction `json:"cacheExpirationAction,omitempty" tf:"cache_expiration_action,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	CacheKeyQueryStringAction []CdnEndpointSpecDeliveryRuleCacheKeyQueryStringAction `json:"cacheKeyQueryStringAction,omitempty" tf:"cache_key_query_string_action,omitempty"`
	// +optional
	CookiesCondition []CdnEndpointSpecDeliveryRuleCookiesCondition `json:"cookiesCondition,omitempty" tf:"cookies_condition,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	DeviceCondition []CdnEndpointSpecDeliveryRuleDeviceCondition `json:"deviceCondition,omitempty" tf:"device_condition,omitempty"`
	// +optional
	HttpVersionCondition []CdnEndpointSpecDeliveryRuleHttpVersionCondition `json:"httpVersionCondition,omitempty" tf:"http_version_condition,omitempty"`
	// +optional
	ModifyRequestHeaderAction []CdnEndpointSpecDeliveryRuleModifyRequestHeaderAction `json:"modifyRequestHeaderAction,omitempty" tf:"modify_request_header_action,omitempty"`
	// +optional
	ModifyResponseHeaderAction []CdnEndpointSpecDeliveryRuleModifyResponseHeaderAction `json:"modifyResponseHeaderAction,omitempty" tf:"modify_response_header_action,omitempty"`
	Name                       string                                                  `json:"name" tf:"name"`
	Order                      int64                                                   `json:"order" tf:"order"`
	// +optional
	PostArgCondition []CdnEndpointSpecDeliveryRulePostArgCondition `json:"postArgCondition,omitempty" tf:"post_arg_condition,omitempty"`
	// +optional
	QueryStringCondition []CdnEndpointSpecDeliveryRuleQueryStringCondition `json:"queryStringCondition,omitempty" tf:"query_string_condition,omitempty"`
	// +optional
	RemoteAddressCondition []CdnEndpointSpecDeliveryRuleRemoteAddressCondition `json:"remoteAddressCondition,omitempty" tf:"remote_address_condition,omitempty"`
	// +optional
	RequestBodyCondition []CdnEndpointSpecDeliveryRuleRequestBodyCondition `json:"requestBodyCondition,omitempty" tf:"request_body_condition,omitempty"`
	// +optional
	RequestHeaderCondition []CdnEndpointSpecDeliveryRuleRequestHeaderCondition `json:"requestHeaderCondition,omitempty" tf:"request_header_condition,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	RequestMethodCondition []CdnEndpointSpecDeliveryRuleRequestMethodCondition `json:"requestMethodCondition,omitempty" tf:"request_method_condition,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	RequestSchemeCondition []CdnEndpointSpecDeliveryRuleRequestSchemeCondition `json:"requestSchemeCondition,omitempty" tf:"request_scheme_condition,omitempty"`
	// +optional
	RequestURICondition []CdnEndpointSpecDeliveryRuleRequestURICondition `json:"requestURICondition,omitempty" tf:"request_uri_condition,omitempty"`
	// +optional
	UrlFileExtensionCondition []CdnEndpointSpecDeliveryRuleUrlFileExtensionCondition `json:"urlFileExtensionCondition,omitempty" tf:"url_file_extension_condition,omitempty"`
	// +optional
	UrlFileNameCondition []CdnEndpointSpecDeliveryRuleUrlFileNameCondition `json:"urlFileNameCondition,omitempty" tf:"url_file_name_condition,omitempty"`
	// +optional
	UrlPathCondition []CdnEndpointSpecDeliveryRuleUrlPathCondition `json:"urlPathCondition,omitempty" tf:"url_path_condition,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	UrlRedirectAction []CdnEndpointSpecDeliveryRuleUrlRedirectAction `json:"urlRedirectAction,omitempty" tf:"url_redirect_action,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	UrlRewriteAction []CdnEndpointSpecDeliveryRuleUrlRewriteAction `json:"urlRewriteAction,omitempty" tf:"url_rewrite_action,omitempty"`
}

type CdnEndpointSpecGeoFilter struct {
	Action       string   `json:"action" tf:"action"`
	CountryCodes []string `json:"countryCodes" tf:"country_codes"`
	RelativePath string   `json:"relativePath" tf:"relative_path"`
}

type CdnEndpointSpecGlobalDeliveryRuleCacheExpirationAction struct {
	Behavior string `json:"behavior" tf:"behavior"`
	// +optional
	Duration string `json:"duration,omitempty" tf:"duration,omitempty"`
}

type CdnEndpointSpecGlobalDeliveryRuleCacheKeyQueryStringAction struct {
	Behavior string `json:"behavior" tf:"behavior"`
	// +optional
	Parameters string `json:"parameters,omitempty" tf:"parameters,omitempty"`
}

type CdnEndpointSpecGlobalDeliveryRuleModifyRequestHeaderAction struct {
	Action string `json:"action" tf:"action"`
	Name   string `json:"name" tf:"name"`
	// +optional
	Value string `json:"value,omitempty" tf:"value,omitempty"`
}

type CdnEndpointSpecGlobalDeliveryRuleModifyResponseHeaderAction struct {
	Action string `json:"action" tf:"action"`
	Name   string `json:"name" tf:"name"`
	// +optional
	Value string `json:"value,omitempty" tf:"value,omitempty"`
}

type CdnEndpointSpecGlobalDeliveryRuleUrlRedirectAction struct {
	// +optional
	Fragment string `json:"fragment,omitempty" tf:"fragment,omitempty"`
	// +optional
	Hostname string `json:"hostname,omitempty" tf:"hostname,omitempty"`
	// +optional
	Path string `json:"path,omitempty" tf:"path,omitempty"`
	// +optional
	Protocol string `json:"protocol,omitempty" tf:"protocol,omitempty"`
	// +optional
	QueryString  string `json:"queryString,omitempty" tf:"query_string,omitempty"`
	RedirectType string `json:"redirectType" tf:"redirect_type"`
}

type CdnEndpointSpecGlobalDeliveryRuleUrlRewriteAction struct {
	Destination string `json:"destination" tf:"destination"`
	// +optional
	PreserveUnmatchedPath bool   `json:"preserveUnmatchedPath,omitempty" tf:"preserve_unmatched_path,omitempty"`
	SourcePattern         string `json:"sourcePattern" tf:"source_pattern"`
}

type CdnEndpointSpecGlobalDeliveryRule struct {
	// +optional
	// +kubebuilder:validation:MaxItems=1
	CacheExpirationAction []CdnEndpointSpecGlobalDeliveryRuleCacheExpirationAction `json:"cacheExpirationAction,omitempty" tf:"cache_expiration_action,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	CacheKeyQueryStringAction []CdnEndpointSpecGlobalDeliveryRuleCacheKeyQueryStringAction `json:"cacheKeyQueryStringAction,omitempty" tf:"cache_key_query_string_action,omitempty"`
	// +optional
	ModifyRequestHeaderAction []CdnEndpointSpecGlobalDeliveryRuleModifyRequestHeaderAction `json:"modifyRequestHeaderAction,omitempty" tf:"modify_request_header_action,omitempty"`
	// +optional
	ModifyResponseHeaderAction []CdnEndpointSpecGlobalDeliveryRuleModifyResponseHeaderAction `json:"modifyResponseHeaderAction,omitempty" tf:"modify_response_header_action,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	UrlRedirectAction []CdnEndpointSpecGlobalDeliveryRuleUrlRedirectAction `json:"urlRedirectAction,omitempty" tf:"url_redirect_action,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	UrlRewriteAction []CdnEndpointSpecGlobalDeliveryRuleUrlRewriteAction `json:"urlRewriteAction,omitempty" tf:"url_rewrite_action,omitempty"`
}

type CdnEndpointSpecOrigin struct {
	HostName string `json:"hostName" tf:"host_name"`
	// +optional
	HttpPort int64 `json:"httpPort,omitempty" tf:"http_port,omitempty"`
	// +optional
	HttpsPort int64  `json:"httpsPort,omitempty" tf:"https_port,omitempty"`
	Name      string `json:"name" tf:"name"`
}

type CdnEndpointSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-"`

	ID string `json:"id,omitempty" tf:"id,omitempty"`

	// +optional
	ContentTypesToCompress []string `json:"contentTypesToCompress,omitempty" tf:"content_types_to_compress,omitempty"`
	// +optional
	DeliveryRule []CdnEndpointSpecDeliveryRule `json:"deliveryRule,omitempty" tf:"delivery_rule,omitempty"`
	// +optional
	GeoFilter []CdnEndpointSpecGeoFilter `json:"geoFilter,omitempty" tf:"geo_filter,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	GlobalDeliveryRule []CdnEndpointSpecGlobalDeliveryRule `json:"globalDeliveryRule,omitempty" tf:"global_delivery_rule,omitempty"`
	// +optional
	HostName string `json:"hostName,omitempty" tf:"host_name,omitempty"`
	// +optional
	IsCompressionEnabled bool `json:"isCompressionEnabled,omitempty" tf:"is_compression_enabled,omitempty"`
	// +optional
	IsHTTPAllowed bool `json:"isHTTPAllowed,omitempty" tf:"is_http_allowed,omitempty"`
	// +optional
	IsHTTPSAllowed bool   `json:"isHTTPSAllowed,omitempty" tf:"is_https_allowed,omitempty"`
	Location       string `json:"location" tf:"location"`
	Name           string `json:"name" tf:"name"`
	// +optional
	OptimizationType string                  `json:"optimizationType,omitempty" tf:"optimization_type,omitempty"`
	Origin           []CdnEndpointSpecOrigin `json:"origin" tf:"origin"`
	// +optional
	OriginHostHeader string `json:"originHostHeader,omitempty" tf:"origin_host_header,omitempty"`
	// +optional
	OriginPath string `json:"originPath,omitempty" tf:"origin_path,omitempty"`
	// +optional
	ProbePath   string `json:"probePath,omitempty" tf:"probe_path,omitempty"`
	ProfileName string `json:"profileName" tf:"profile_name"`
	// +optional
	QuerystringCachingBehaviour string `json:"querystringCachingBehaviour,omitempty" tf:"querystring_caching_behaviour,omitempty"`
	ResourceGroupName           string `json:"resourceGroupName" tf:"resource_group_name"`
	// +optional
	Tags map[string]string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type CdnEndpointStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	// +optional
	Output *CdnEndpointSpec `json:"output,omitempty"`
	// +optional
	State *base.State `json:"state,omitempty"`
	// +optional
	Phase base.Phase `json:"phase,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// CdnEndpointList is a list of CdnEndpoints
type CdnEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	// Items is a list of CdnEndpoint CRD objects
	Items []CdnEndpoint `json:"items,omitempty"`
}
