/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// FakeNatGatewayPublicIPAssociations implements NatGatewayPublicIPAssociationInterface
type FakeNatGatewayPublicIPAssociations struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var natgatewaypublicipassociationsResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "natgatewaypublicipassociations"}

var natgatewaypublicipassociationsKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "NatGatewayPublicIPAssociation"}

// Get takes name of the natGatewayPublicIPAssociation, and returns the corresponding natGatewayPublicIPAssociation object, and an error if there is any.
func (c *FakeNatGatewayPublicIPAssociations) Get(name string, options v1.GetOptions) (result *v1alpha1.NatGatewayPublicIPAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(natgatewaypublicipassociationsResource, c.ns, name), &v1alpha1.NatGatewayPublicIPAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NatGatewayPublicIPAssociation), err
}

// List takes label and field selectors, and returns the list of NatGatewayPublicIPAssociations that match those selectors.
func (c *FakeNatGatewayPublicIPAssociations) List(opts v1.ListOptions) (result *v1alpha1.NatGatewayPublicIPAssociationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(natgatewaypublicipassociationsResource, natgatewaypublicipassociationsKind, c.ns, opts), &v1alpha1.NatGatewayPublicIPAssociationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NatGatewayPublicIPAssociationList{ListMeta: obj.(*v1alpha1.NatGatewayPublicIPAssociationList).ListMeta}
	for _, item := range obj.(*v1alpha1.NatGatewayPublicIPAssociationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested natGatewayPublicIPAssociations.
func (c *FakeNatGatewayPublicIPAssociations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(natgatewaypublicipassociationsResource, c.ns, opts))

}

// Create takes the representation of a natGatewayPublicIPAssociation and creates it.  Returns the server's representation of the natGatewayPublicIPAssociation, and an error, if there is any.
func (c *FakeNatGatewayPublicIPAssociations) Create(natGatewayPublicIPAssociation *v1alpha1.NatGatewayPublicIPAssociation) (result *v1alpha1.NatGatewayPublicIPAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(natgatewaypublicipassociationsResource, c.ns, natGatewayPublicIPAssociation), &v1alpha1.NatGatewayPublicIPAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NatGatewayPublicIPAssociation), err
}

// Update takes the representation of a natGatewayPublicIPAssociation and updates it. Returns the server's representation of the natGatewayPublicIPAssociation, and an error, if there is any.
func (c *FakeNatGatewayPublicIPAssociations) Update(natGatewayPublicIPAssociation *v1alpha1.NatGatewayPublicIPAssociation) (result *v1alpha1.NatGatewayPublicIPAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(natgatewaypublicipassociationsResource, c.ns, natGatewayPublicIPAssociation), &v1alpha1.NatGatewayPublicIPAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NatGatewayPublicIPAssociation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNatGatewayPublicIPAssociations) UpdateStatus(natGatewayPublicIPAssociation *v1alpha1.NatGatewayPublicIPAssociation) (*v1alpha1.NatGatewayPublicIPAssociation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(natgatewaypublicipassociationsResource, "status", c.ns, natGatewayPublicIPAssociation), &v1alpha1.NatGatewayPublicIPAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NatGatewayPublicIPAssociation), err
}

// Delete takes name of the natGatewayPublicIPAssociation and deletes it. Returns an error if one occurs.
func (c *FakeNatGatewayPublicIPAssociations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(natgatewaypublicipassociationsResource, c.ns, name), &v1alpha1.NatGatewayPublicIPAssociation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNatGatewayPublicIPAssociations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(natgatewaypublicipassociationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NatGatewayPublicIPAssociationList{})
	return err
}

// Patch applies the patch and returns the patched natGatewayPublicIPAssociation.
func (c *FakeNatGatewayPublicIPAssociations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NatGatewayPublicIPAssociation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(natgatewaypublicipassociationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NatGatewayPublicIPAssociation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NatGatewayPublicIPAssociation), err
}
