/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// FakeHpcCaches implements HpcCacheInterface
type FakeHpcCaches struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var hpccachesResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "hpccaches"}

var hpccachesKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "HpcCache"}

// Get takes name of the hpcCache, and returns the corresponding hpcCache object, and an error if there is any.
func (c *FakeHpcCaches) Get(name string, options v1.GetOptions) (result *v1alpha1.HpcCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hpccachesResource, c.ns, name), &v1alpha1.HpcCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HpcCache), err
}

// List takes label and field selectors, and returns the list of HpcCaches that match those selectors.
func (c *FakeHpcCaches) List(opts v1.ListOptions) (result *v1alpha1.HpcCacheList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hpccachesResource, hpccachesKind, c.ns, opts), &v1alpha1.HpcCacheList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HpcCacheList{ListMeta: obj.(*v1alpha1.HpcCacheList).ListMeta}
	for _, item := range obj.(*v1alpha1.HpcCacheList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hpcCaches.
func (c *FakeHpcCaches) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hpccachesResource, c.ns, opts))

}

// Create takes the representation of a hpcCache and creates it.  Returns the server's representation of the hpcCache, and an error, if there is any.
func (c *FakeHpcCaches) Create(hpcCache *v1alpha1.HpcCache) (result *v1alpha1.HpcCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hpccachesResource, c.ns, hpcCache), &v1alpha1.HpcCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HpcCache), err
}

// Update takes the representation of a hpcCache and updates it. Returns the server's representation of the hpcCache, and an error, if there is any.
func (c *FakeHpcCaches) Update(hpcCache *v1alpha1.HpcCache) (result *v1alpha1.HpcCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hpccachesResource, c.ns, hpcCache), &v1alpha1.HpcCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HpcCache), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHpcCaches) UpdateStatus(hpcCache *v1alpha1.HpcCache) (*v1alpha1.HpcCache, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hpccachesResource, "status", c.ns, hpcCache), &v1alpha1.HpcCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HpcCache), err
}

// Delete takes name of the hpcCache and deletes it. Returns an error if one occurs.
func (c *FakeHpcCaches) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hpccachesResource, c.ns, name), &v1alpha1.HpcCache{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHpcCaches) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hpccachesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.HpcCacheList{})
	return err
}

// Patch applies the patch and returns the patched hpcCache.
func (c *FakeHpcCaches) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.HpcCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hpccachesResource, c.ns, name, pt, data, subresources...), &v1alpha1.HpcCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HpcCache), err
}
