/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// FakeEventgridDomainTopics implements EventgridDomainTopicInterface
type FakeEventgridDomainTopics struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var eventgriddomaintopicsResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "eventgriddomaintopics"}

var eventgriddomaintopicsKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "EventgridDomainTopic"}

// Get takes name of the eventgridDomainTopic, and returns the corresponding eventgridDomainTopic object, and an error if there is any.
func (c *FakeEventgridDomainTopics) Get(name string, options v1.GetOptions) (result *v1alpha1.EventgridDomainTopic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(eventgriddomaintopicsResource, c.ns, name), &v1alpha1.EventgridDomainTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventgridDomainTopic), err
}

// List takes label and field selectors, and returns the list of EventgridDomainTopics that match those selectors.
func (c *FakeEventgridDomainTopics) List(opts v1.ListOptions) (result *v1alpha1.EventgridDomainTopicList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(eventgriddomaintopicsResource, eventgriddomaintopicsKind, c.ns, opts), &v1alpha1.EventgridDomainTopicList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EventgridDomainTopicList{ListMeta: obj.(*v1alpha1.EventgridDomainTopicList).ListMeta}
	for _, item := range obj.(*v1alpha1.EventgridDomainTopicList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested eventgridDomainTopics.
func (c *FakeEventgridDomainTopics) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(eventgriddomaintopicsResource, c.ns, opts))

}

// Create takes the representation of a eventgridDomainTopic and creates it.  Returns the server's representation of the eventgridDomainTopic, and an error, if there is any.
func (c *FakeEventgridDomainTopics) Create(eventgridDomainTopic *v1alpha1.EventgridDomainTopic) (result *v1alpha1.EventgridDomainTopic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(eventgriddomaintopicsResource, c.ns, eventgridDomainTopic), &v1alpha1.EventgridDomainTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventgridDomainTopic), err
}

// Update takes the representation of a eventgridDomainTopic and updates it. Returns the server's representation of the eventgridDomainTopic, and an error, if there is any.
func (c *FakeEventgridDomainTopics) Update(eventgridDomainTopic *v1alpha1.EventgridDomainTopic) (result *v1alpha1.EventgridDomainTopic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(eventgriddomaintopicsResource, c.ns, eventgridDomainTopic), &v1alpha1.EventgridDomainTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventgridDomainTopic), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEventgridDomainTopics) UpdateStatus(eventgridDomainTopic *v1alpha1.EventgridDomainTopic) (*v1alpha1.EventgridDomainTopic, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(eventgriddomaintopicsResource, "status", c.ns, eventgridDomainTopic), &v1alpha1.EventgridDomainTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventgridDomainTopic), err
}

// Delete takes name of the eventgridDomainTopic and deletes it. Returns an error if one occurs.
func (c *FakeEventgridDomainTopics) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(eventgriddomaintopicsResource, c.ns, name), &v1alpha1.EventgridDomainTopic{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEventgridDomainTopics) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(eventgriddomaintopicsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.EventgridDomainTopicList{})
	return err
}

// Patch applies the patch and returns the patched eventgridDomainTopic.
func (c *FakeEventgridDomainTopics) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EventgridDomainTopic, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(eventgriddomaintopicsResource, c.ns, name, pt, data, subresources...), &v1alpha1.EventgridDomainTopic{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EventgridDomainTopic), err
}
