/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// FakeDataShares implements DataShareInterface
type FakeDataShares struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var datasharesResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "datashares"}

var datasharesKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "DataShare"}

// Get takes name of the dataShare, and returns the corresponding dataShare object, and an error if there is any.
func (c *FakeDataShares) Get(name string, options v1.GetOptions) (result *v1alpha1.DataShare, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(datasharesResource, c.ns, name), &v1alpha1.DataShare{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataShare), err
}

// List takes label and field selectors, and returns the list of DataShares that match those selectors.
func (c *FakeDataShares) List(opts v1.ListOptions) (result *v1alpha1.DataShareList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(datasharesResource, datasharesKind, c.ns, opts), &v1alpha1.DataShareList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DataShareList{ListMeta: obj.(*v1alpha1.DataShareList).ListMeta}
	for _, item := range obj.(*v1alpha1.DataShareList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dataShares.
func (c *FakeDataShares) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(datasharesResource, c.ns, opts))

}

// Create takes the representation of a dataShare and creates it.  Returns the server's representation of the dataShare, and an error, if there is any.
func (c *FakeDataShares) Create(dataShare *v1alpha1.DataShare) (result *v1alpha1.DataShare, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(datasharesResource, c.ns, dataShare), &v1alpha1.DataShare{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataShare), err
}

// Update takes the representation of a dataShare and updates it. Returns the server's representation of the dataShare, and an error, if there is any.
func (c *FakeDataShares) Update(dataShare *v1alpha1.DataShare) (result *v1alpha1.DataShare, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(datasharesResource, c.ns, dataShare), &v1alpha1.DataShare{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataShare), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDataShares) UpdateStatus(dataShare *v1alpha1.DataShare) (*v1alpha1.DataShare, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(datasharesResource, "status", c.ns, dataShare), &v1alpha1.DataShare{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataShare), err
}

// Delete takes name of the dataShare and deletes it. Returns an error if one occurs.
func (c *FakeDataShares) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(datasharesResource, c.ns, name), &v1alpha1.DataShare{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataShares) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(datasharesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DataShareList{})
	return err
}

// Patch applies the patch and returns the patched dataShare.
func (c *FakeDataShares) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DataShare, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(datasharesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DataShare{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataShare), err
}
