/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// FakeCustomProviders implements CustomProviderInterface
type FakeCustomProviders struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var customprovidersResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "customproviders"}

var customprovidersKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "CustomProvider"}

// Get takes name of the customProvider, and returns the corresponding customProvider object, and an error if there is any.
func (c *FakeCustomProviders) Get(name string, options v1.GetOptions) (result *v1alpha1.CustomProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customprovidersResource, c.ns, name), &v1alpha1.CustomProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomProvider), err
}

// List takes label and field selectors, and returns the list of CustomProviders that match those selectors.
func (c *FakeCustomProviders) List(opts v1.ListOptions) (result *v1alpha1.CustomProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customprovidersResource, customprovidersKind, c.ns, opts), &v1alpha1.CustomProviderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomProviderList{ListMeta: obj.(*v1alpha1.CustomProviderList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customProviders.
func (c *FakeCustomProviders) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customprovidersResource, c.ns, opts))

}

// Create takes the representation of a customProvider and creates it.  Returns the server's representation of the customProvider, and an error, if there is any.
func (c *FakeCustomProviders) Create(customProvider *v1alpha1.CustomProvider) (result *v1alpha1.CustomProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customprovidersResource, c.ns, customProvider), &v1alpha1.CustomProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomProvider), err
}

// Update takes the representation of a customProvider and updates it. Returns the server's representation of the customProvider, and an error, if there is any.
func (c *FakeCustomProviders) Update(customProvider *v1alpha1.CustomProvider) (result *v1alpha1.CustomProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customprovidersResource, c.ns, customProvider), &v1alpha1.CustomProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomProvider), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCustomProviders) UpdateStatus(customProvider *v1alpha1.CustomProvider) (*v1alpha1.CustomProvider, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(customprovidersResource, "status", c.ns, customProvider), &v1alpha1.CustomProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomProvider), err
}

// Delete takes name of the customProvider and deletes it. Returns an error if one occurs.
func (c *FakeCustomProviders) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customprovidersResource, c.ns, name), &v1alpha1.CustomProvider{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomProviders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customprovidersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomProviderList{})
	return err
}

// Patch applies the patch and returns the patched customProvider.
func (c *FakeCustomProviders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customprovidersResource, c.ns, name, pt, data, subresources...), &v1alpha1.CustomProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomProvider), err
}
