/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// FakeBlueprintAssignments implements BlueprintAssignmentInterface
type FakeBlueprintAssignments struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var blueprintassignmentsResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "blueprintassignments"}

var blueprintassignmentsKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "BlueprintAssignment"}

// Get takes name of the blueprintAssignment, and returns the corresponding blueprintAssignment object, and an error if there is any.
func (c *FakeBlueprintAssignments) Get(name string, options v1.GetOptions) (result *v1alpha1.BlueprintAssignment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(blueprintassignmentsResource, c.ns, name), &v1alpha1.BlueprintAssignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueprintAssignment), err
}

// List takes label and field selectors, and returns the list of BlueprintAssignments that match those selectors.
func (c *FakeBlueprintAssignments) List(opts v1.ListOptions) (result *v1alpha1.BlueprintAssignmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(blueprintassignmentsResource, blueprintassignmentsKind, c.ns, opts), &v1alpha1.BlueprintAssignmentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BlueprintAssignmentList{ListMeta: obj.(*v1alpha1.BlueprintAssignmentList).ListMeta}
	for _, item := range obj.(*v1alpha1.BlueprintAssignmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested blueprintAssignments.
func (c *FakeBlueprintAssignments) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(blueprintassignmentsResource, c.ns, opts))

}

// Create takes the representation of a blueprintAssignment and creates it.  Returns the server's representation of the blueprintAssignment, and an error, if there is any.
func (c *FakeBlueprintAssignments) Create(blueprintAssignment *v1alpha1.BlueprintAssignment) (result *v1alpha1.BlueprintAssignment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(blueprintassignmentsResource, c.ns, blueprintAssignment), &v1alpha1.BlueprintAssignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueprintAssignment), err
}

// Update takes the representation of a blueprintAssignment and updates it. Returns the server's representation of the blueprintAssignment, and an error, if there is any.
func (c *FakeBlueprintAssignments) Update(blueprintAssignment *v1alpha1.BlueprintAssignment) (result *v1alpha1.BlueprintAssignment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(blueprintassignmentsResource, c.ns, blueprintAssignment), &v1alpha1.BlueprintAssignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueprintAssignment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBlueprintAssignments) UpdateStatus(blueprintAssignment *v1alpha1.BlueprintAssignment) (*v1alpha1.BlueprintAssignment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(blueprintassignmentsResource, "status", c.ns, blueprintAssignment), &v1alpha1.BlueprintAssignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueprintAssignment), err
}

// Delete takes name of the blueprintAssignment and deletes it. Returns an error if one occurs.
func (c *FakeBlueprintAssignments) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(blueprintassignmentsResource, c.ns, name), &v1alpha1.BlueprintAssignment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBlueprintAssignments) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(blueprintassignmentsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BlueprintAssignmentList{})
	return err
}

// Patch applies the patch and returns the patched blueprintAssignment.
func (c *FakeBlueprintAssignments) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BlueprintAssignment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(blueprintassignmentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BlueprintAssignment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BlueprintAssignment), err
}
