/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// FakeSpatialAnchorsAccounts implements SpatialAnchorsAccountInterface
type FakeSpatialAnchorsAccounts struct {
	Fake *FakeAzurermV1alpha1
	ns   string
}

var spatialanchorsaccountsResource = schema.GroupVersionResource{Group: "azurerm.kubeform.com", Version: "v1alpha1", Resource: "spatialanchorsaccounts"}

var spatialanchorsaccountsKind = schema.GroupVersionKind{Group: "azurerm.kubeform.com", Version: "v1alpha1", Kind: "SpatialAnchorsAccount"}

// Get takes name of the spatialAnchorsAccount, and returns the corresponding spatialAnchorsAccount object, and an error if there is any.
func (c *FakeSpatialAnchorsAccounts) Get(name string, options v1.GetOptions) (result *v1alpha1.SpatialAnchorsAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(spatialanchorsaccountsResource, c.ns, name), &v1alpha1.SpatialAnchorsAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpatialAnchorsAccount), err
}

// List takes label and field selectors, and returns the list of SpatialAnchorsAccounts that match those selectors.
func (c *FakeSpatialAnchorsAccounts) List(opts v1.ListOptions) (result *v1alpha1.SpatialAnchorsAccountList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(spatialanchorsaccountsResource, spatialanchorsaccountsKind, c.ns, opts), &v1alpha1.SpatialAnchorsAccountList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SpatialAnchorsAccountList{ListMeta: obj.(*v1alpha1.SpatialAnchorsAccountList).ListMeta}
	for _, item := range obj.(*v1alpha1.SpatialAnchorsAccountList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested spatialAnchorsAccounts.
func (c *FakeSpatialAnchorsAccounts) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(spatialanchorsaccountsResource, c.ns, opts))

}

// Create takes the representation of a spatialAnchorsAccount and creates it.  Returns the server's representation of the spatialAnchorsAccount, and an error, if there is any.
func (c *FakeSpatialAnchorsAccounts) Create(spatialAnchorsAccount *v1alpha1.SpatialAnchorsAccount) (result *v1alpha1.SpatialAnchorsAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(spatialanchorsaccountsResource, c.ns, spatialAnchorsAccount), &v1alpha1.SpatialAnchorsAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpatialAnchorsAccount), err
}

// Update takes the representation of a spatialAnchorsAccount and updates it. Returns the server's representation of the spatialAnchorsAccount, and an error, if there is any.
func (c *FakeSpatialAnchorsAccounts) Update(spatialAnchorsAccount *v1alpha1.SpatialAnchorsAccount) (result *v1alpha1.SpatialAnchorsAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(spatialanchorsaccountsResource, c.ns, spatialAnchorsAccount), &v1alpha1.SpatialAnchorsAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpatialAnchorsAccount), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSpatialAnchorsAccounts) UpdateStatus(spatialAnchorsAccount *v1alpha1.SpatialAnchorsAccount) (*v1alpha1.SpatialAnchorsAccount, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(spatialanchorsaccountsResource, "status", c.ns, spatialAnchorsAccount), &v1alpha1.SpatialAnchorsAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpatialAnchorsAccount), err
}

// Delete takes name of the spatialAnchorsAccount and deletes it. Returns an error if one occurs.
func (c *FakeSpatialAnchorsAccounts) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(spatialanchorsaccountsResource, c.ns, name), &v1alpha1.SpatialAnchorsAccount{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSpatialAnchorsAccounts) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(spatialanchorsaccountsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SpatialAnchorsAccountList{})
	return err
}

// Patch applies the patch and returns the patched spatialAnchorsAccount.
func (c *FakeSpatialAnchorsAccounts) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SpatialAnchorsAccount, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(spatialanchorsaccountsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SpatialAnchorsAccount{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SpatialAnchorsAccount), err
}
