/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha1

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha1"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type MonitorScheduledQueryRulesLog struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MonitorScheduledQueryRulesLogSpec   `json:"spec,omitempty"`
	Status            MonitorScheduledQueryRulesLogStatus `json:"status,omitempty"`
}

type MonitorScheduledQueryRulesLogSpecCriteriaDimension struct {
	Name string `json:"name" tf:"name"`
	// +optional
	Operator string   `json:"operator,omitempty" tf:"operator,omitempty"`
	Values   []string `json:"values" tf:"values"`
}

type MonitorScheduledQueryRulesLogSpecCriteria struct {
	Dimension  []MonitorScheduledQueryRulesLogSpecCriteriaDimension `json:"dimension" tf:"dimension"`
	MetricName string                                               `json:"metricName" tf:"metric_name"`
}

type MonitorScheduledQueryRulesLogSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-"`

	ID string `json:"id,omitempty" tf:"id,omitempty"`

	// +optional
	AuthorizedResourceIDS []string `json:"authorizedResourceIDS,omitempty" tf:"authorized_resource_ids,omitempty"`
	// +kubebuilder:validation:MaxItems=1
	Criteria     []MonitorScheduledQueryRulesLogSpecCriteria `json:"criteria" tf:"criteria"`
	DataSourceID string                                      `json:"dataSourceID" tf:"data_source_id"`
	// +optional
	Description string `json:"description,omitempty" tf:"description,omitempty"`
	// +optional
	Enabled           bool   `json:"enabled,omitempty" tf:"enabled,omitempty"`
	Location          string `json:"location" tf:"location"`
	Name              string `json:"name" tf:"name"`
	ResourceGroupName string `json:"resourceGroupName" tf:"resource_group_name"`
	// +optional
	Tags map[string]string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type MonitorScheduledQueryRulesLogStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	// +optional
	Output *MonitorScheduledQueryRulesLogSpec `json:"output,omitempty"`
	// +optional
	State *base.State `json:"state,omitempty"`
	// +optional
	Phase base.Phase `json:"phase,omitempty"`
	// +optional
	TerraFormLogs *base.TerraFormLogs `json:"terraformLogs,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// MonitorScheduledQueryRulesLogList is a list of MonitorScheduledQueryRulesLogs
type MonitorScheduledQueryRulesLogList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	// Items is a list of MonitorScheduledQueryRulesLog CRD objects
	Items []MonitorScheduledQueryRulesLog `json:"items,omitempty"`
}
