/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package v1alpha1

import (
	base "kubeform.dev/kubeform/apis/base/v1alpha1"

	core "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:openapi-gen=true
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type=string,JSONPath=`.status.phase`

type WindowsVirtualMachine struct {
	metav1.TypeMeta   `json:",inline,omitempty"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WindowsVirtualMachineSpec   `json:"spec,omitempty"`
	Status            WindowsVirtualMachineStatus `json:"status,omitempty"`
}

type WindowsVirtualMachineSpecAdditionalCapabilities struct {
	// +optional
	UltraSsdEnabled bool `json:"ultraSsdEnabled,omitempty" tf:"ultra_ssd_enabled,omitempty"`
}

type WindowsVirtualMachineSpecAdditionalUnattendContent struct {
	Content string `json:"-" sensitive:"true" tf:"content"`
	Setting string `json:"setting" tf:"setting"`
}

type WindowsVirtualMachineSpecBootDiagnostics struct {
	StorageAccountURI string `json:"storageAccountURI" tf:"storage_account_uri"`
}

type WindowsVirtualMachineSpecIdentity struct {
	// +optional
	IdentityIDS []string `json:"identityIDS,omitempty" tf:"identity_ids,omitempty"`
	// +optional
	PrincipalID string `json:"principalID,omitempty" tf:"principal_id,omitempty"`
	// +optional
	TenantID string `json:"tenantID,omitempty" tf:"tenant_id,omitempty"`
	Type     string `json:"type" tf:"type"`
}

type WindowsVirtualMachineSpecOsDiskDiffDiskSettings struct {
	Option string `json:"option" tf:"option"`
}

type WindowsVirtualMachineSpecOsDisk struct {
	Caching string `json:"caching" tf:"caching"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	DiffDiskSettings []WindowsVirtualMachineSpecOsDiskDiffDiskSettings `json:"diffDiskSettings,omitempty" tf:"diff_disk_settings,omitempty"`
	// +optional
	DiskEncryptionSetID string `json:"diskEncryptionSetID,omitempty" tf:"disk_encryption_set_id,omitempty"`
	// +optional
	DiskSizeGb int64 `json:"diskSizeGb,omitempty" tf:"disk_size_gb,omitempty"`
	// +optional
	Name               string `json:"name,omitempty" tf:"name,omitempty"`
	StorageAccountType string `json:"storageAccountType" tf:"storage_account_type"`
	// +optional
	WriteAcceleratorEnabled bool `json:"writeAcceleratorEnabled,omitempty" tf:"write_accelerator_enabled,omitempty"`
}

type WindowsVirtualMachineSpecPlan struct {
	Name      string `json:"name" tf:"name"`
	Product   string `json:"product" tf:"product"`
	Publisher string `json:"publisher" tf:"publisher"`
}

type WindowsVirtualMachineSpecSecretCertificate struct {
	Store string `json:"store" tf:"store"`
	Url   string `json:"url" tf:"url"`
}

type WindowsVirtualMachineSpecSecret struct {
	// +kubebuilder:validation:MinItems=1
	Certificate []WindowsVirtualMachineSpecSecretCertificate `json:"certificate" tf:"certificate"`
	KeyVaultID  string                                       `json:"keyVaultID" tf:"key_vault_id"`
}

type WindowsVirtualMachineSpecSourceImageReference struct {
	Offer     string `json:"offer" tf:"offer"`
	Publisher string `json:"publisher" tf:"publisher"`
	Sku       string `json:"sku" tf:"sku"`
	Version   string `json:"version" tf:"version"`
}

type WindowsVirtualMachineSpecWinrmListener struct {
	// +optional
	CertificateURL string `json:"certificateURL,omitempty" tf:"certificate_url,omitempty"`
	Protocol       string `json:"protocol" tf:"protocol"`
}

type WindowsVirtualMachineSpec struct {
	ProviderRef core.LocalObjectReference `json:"providerRef" tf:"-"`

	ID string `json:"id,omitempty" tf:"id,omitempty"`

	SecretRef *core.LocalObjectReference `json:"secretRef,omitempty" tf:"-"`

	// +optional
	// +kubebuilder:validation:MaxItems=1
	AdditionalCapabilities []WindowsVirtualMachineSpecAdditionalCapabilities `json:"additionalCapabilities,omitempty" tf:"additional_capabilities,omitempty"`
	// +optional
	AdditionalUnattendContent []WindowsVirtualMachineSpecAdditionalUnattendContent `json:"additionalUnattendContent,omitempty" tf:"additional_unattend_content,omitempty"`
	AdminPassword             string                                               `json:"-" sensitive:"true" tf:"admin_password"`
	AdminUsername             string                                               `json:"adminUsername" tf:"admin_username"`
	// +optional
	AllowExtensionOperations bool `json:"allowExtensionOperations,omitempty" tf:"allow_extension_operations,omitempty"`
	// +optional
	AvailabilitySetID string `json:"availabilitySetID,omitempty" tf:"availability_set_id,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	BootDiagnostics []WindowsVirtualMachineSpecBootDiagnostics `json:"bootDiagnostics,omitempty" tf:"boot_diagnostics,omitempty"`
	// +optional
	ComputerName string `json:"computerName,omitempty" tf:"computer_name,omitempty"`
	// +optional
	CustomData string `json:"-" sensitive:"true" tf:"custom_data,omitempty"`
	// +optional
	DedicatedHostID string `json:"dedicatedHostID,omitempty" tf:"dedicated_host_id,omitempty"`
	// +optional
	EnableAutomaticUpdates bool `json:"enableAutomaticUpdates,omitempty" tf:"enable_automatic_updates,omitempty"`
	// +optional
	EvictionPolicy string `json:"evictionPolicy,omitempty" tf:"eviction_policy,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	Identity []WindowsVirtualMachineSpecIdentity `json:"identity,omitempty" tf:"identity,omitempty"`
	// +optional
	LicenseType string `json:"licenseType,omitempty" tf:"license_type,omitempty"`
	Location    string `json:"location" tf:"location"`
	// +optional
	MaxBidPrice float64 `json:"maxBidPrice,omitempty" tf:"max_bid_price,omitempty"`
	Name        string  `json:"name" tf:"name"`
	// +kubebuilder:validation:MinItems=1
	NetworkInterfaceIDS []string `json:"networkInterfaceIDS" tf:"network_interface_ids"`
	// +kubebuilder:validation:MaxItems=1
	OsDisk []WindowsVirtualMachineSpecOsDisk `json:"osDisk" tf:"os_disk"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	Plan []WindowsVirtualMachineSpecPlan `json:"plan,omitempty" tf:"plan,omitempty"`
	// +optional
	Priority string `json:"priority,omitempty" tf:"priority,omitempty"`
	// +optional
	PrivateIPAddress string `json:"privateIPAddress,omitempty" tf:"private_ip_address,omitempty"`
	// +optional
	PrivateIPAddresses []string `json:"privateIPAddresses,omitempty" tf:"private_ip_addresses,omitempty"`
	// +optional
	ProvisionVmAgent bool `json:"provisionVmAgent,omitempty" tf:"provision_vm_agent,omitempty"`
	// +optional
	ProximityPlacementGroupID string `json:"proximityPlacementGroupID,omitempty" tf:"proximity_placement_group_id,omitempty"`
	// +optional
	PublicIPAddress string `json:"publicIPAddress,omitempty" tf:"public_ip_address,omitempty"`
	// +optional
	PublicIPAddresses []string `json:"publicIPAddresses,omitempty" tf:"public_ip_addresses,omitempty"`
	ResourceGroupName string   `json:"resourceGroupName" tf:"resource_group_name"`
	// +optional
	Secret []WindowsVirtualMachineSpecSecret `json:"secret,omitempty" tf:"secret,omitempty"`
	Size   string                            `json:"size" tf:"size"`
	// +optional
	SourceImageID string `json:"sourceImageID,omitempty" tf:"source_image_id,omitempty"`
	// +optional
	// +kubebuilder:validation:MaxItems=1
	SourceImageReference []WindowsVirtualMachineSpecSourceImageReference `json:"sourceImageReference,omitempty" tf:"source_image_reference,omitempty"`
	// +optional
	Tags map[string]string `json:"tags,omitempty" tf:"tags,omitempty"`
	// +optional
	Timezone string `json:"timezone,omitempty" tf:"timezone,omitempty"`
	// +optional
	VirtualMachineID string `json:"virtualMachineID,omitempty" tf:"virtual_machine_id,omitempty"`
	// +optional
	VirtualMachineScaleSetID string `json:"virtualMachineScaleSetID,omitempty" tf:"virtual_machine_scale_set_id,omitempty"`
	// +optional
	WinrmListener []WindowsVirtualMachineSpecWinrmListener `json:"winrmListener,omitempty" tf:"winrm_listener,omitempty"`
	// +optional
	Zone string `json:"zone,omitempty" tf:"zone,omitempty"`
}

type WindowsVirtualMachineStatus struct {
	// Resource generation, which is updated on mutation by the API Server.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
	// +optional
	Output *WindowsVirtualMachineSpec `json:"output,omitempty"`
	// +optional
	State *base.State `json:"state,omitempty"`
	// +optional
	Phase base.Phase `json:"phase,omitempty"`
	// +optional
	TerraFormState string `json:"terraformState,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true

// WindowsVirtualMachineList is a list of WindowsVirtualMachines
type WindowsVirtualMachineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	// Items is a list of WindowsVirtualMachine CRD objects
	Items []WindowsVirtualMachine `json:"items,omitempty"`
}
