apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: windowsvirtualmachines.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: WindowsVirtualMachine
    listKind: WindowsVirtualMachineList
    plural: windowsvirtualmachines
    singular: windowsvirtualmachine
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalCapabilities:
              items:
                properties:
                  ultraSsdEnabled:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            additionalUnattendContent:
              items:
                properties:
                  setting:
                    type: string
                required:
                - setting
                type: object
              type: array
            adminUsername:
              type: string
            allowExtensionOperations:
              type: boolean
            availabilitySetID:
              type: string
            bootDiagnostics:
              items:
                properties:
                  storageAccountURI:
                    type: string
                required:
                - storageAccountURI
                type: object
              maxItems: 1
              type: array
            computerName:
              type: string
            dedicatedHostID:
              type: string
            enableAutomaticUpdates:
              type: boolean
            evictionPolicy:
              type: string
            id:
              type: string
            identity:
              items:
                properties:
                  identityIDS:
                    items:
                      type: string
                    type: array
                  principalID:
                    type: string
                  tenantID:
                    type: string
                  type:
                    type: string
                required:
                - type
                type: object
              maxItems: 1
              type: array
            licenseType:
              type: string
            location:
              type: string
            maxBidPrice:
              format: float
              type: number
            name:
              type: string
            networkInterfaceIDS:
              items:
                type: string
              minItems: 1
              type: array
            osDisk:
              items:
                properties:
                  caching:
                    type: string
                  diffDiskSettings:
                    items:
                      properties:
                        option:
                          type: string
                      required:
                      - option
                      type: object
                    maxItems: 1
                    type: array
                  diskEncryptionSetID:
                    type: string
                  diskSizeGb:
                    format: int64
                    type: integer
                  name:
                    type: string
                  storageAccountType:
                    type: string
                  writeAcceleratorEnabled:
                    type: boolean
                required:
                - caching
                - storageAccountType
                type: object
              maxItems: 1
              type: array
            plan:
              items:
                properties:
                  name:
                    type: string
                  product:
                    type: string
                  publisher:
                    type: string
                required:
                - name
                - product
                - publisher
                type: object
              maxItems: 1
              type: array
            priority:
              type: string
            privateIPAddress:
              type: string
            privateIPAddresses:
              items:
                type: string
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            provisionVmAgent:
              type: boolean
            proximityPlacementGroupID:
              type: string
            publicIPAddress:
              type: string
            publicIPAddresses:
              items:
                type: string
              type: array
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            resourceGroupName:
              type: string
            secret:
              items:
                properties:
                  certificate:
                    items:
                      properties:
                        store:
                          type: string
                        url:
                          type: string
                      required:
                      - store
                      - url
                      type: object
                    minItems: 1
                    type: array
                  keyVaultID:
                    type: string
                required:
                - certificate
                - keyVaultID
                type: object
              type: array
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            size:
              type: string
            sourceImageID:
              type: string
            sourceImageReference:
              items:
                properties:
                  offer:
                    type: string
                  publisher:
                    type: string
                  sku:
                    type: string
                  version:
                    type: string
                required:
                - offer
                - publisher
                - sku
                - version
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            timezone:
              type: string
            virtualMachineID:
              type: string
            virtualMachineScaleSetID:
              type: string
            winrmListener:
              items:
                properties:
                  certificateURL:
                    type: string
                  protocol:
                    type: string
                required:
                - protocol
                type: object
              type: array
            zone:
              type: string
          required:
          - adminUsername
          - location
          - name
          - networkInterfaceIDS
          - osDisk
          - providerRef
          - resourceGroupName
          - size
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                additionalCapabilities:
                  items:
                    properties:
                      ultraSsdEnabled:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                additionalUnattendContent:
                  items:
                    properties:
                      setting:
                        type: string
                    required:
                    - setting
                    type: object
                  type: array
                adminUsername:
                  type: string
                allowExtensionOperations:
                  type: boolean
                availabilitySetID:
                  type: string
                bootDiagnostics:
                  items:
                    properties:
                      storageAccountURI:
                        type: string
                    required:
                    - storageAccountURI
                    type: object
                  maxItems: 1
                  type: array
                computerName:
                  type: string
                dedicatedHostID:
                  type: string
                enableAutomaticUpdates:
                  type: boolean
                evictionPolicy:
                  type: string
                id:
                  type: string
                identity:
                  items:
                    properties:
                      identityIDS:
                        items:
                          type: string
                        type: array
                      principalID:
                        type: string
                      tenantID:
                        type: string
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  maxItems: 1
                  type: array
                licenseType:
                  type: string
                location:
                  type: string
                maxBidPrice:
                  format: float
                  type: number
                name:
                  type: string
                networkInterfaceIDS:
                  items:
                    type: string
                  minItems: 1
                  type: array
                osDisk:
                  items:
                    properties:
                      caching:
                        type: string
                      diffDiskSettings:
                        items:
                          properties:
                            option:
                              type: string
                          required:
                          - option
                          type: object
                        maxItems: 1
                        type: array
                      diskEncryptionSetID:
                        type: string
                      diskSizeGb:
                        format: int64
                        type: integer
                      name:
                        type: string
                      storageAccountType:
                        type: string
                      writeAcceleratorEnabled:
                        type: boolean
                    required:
                    - caching
                    - storageAccountType
                    type: object
                  maxItems: 1
                  type: array
                plan:
                  items:
                    properties:
                      name:
                        type: string
                      product:
                        type: string
                      publisher:
                        type: string
                    required:
                    - name
                    - product
                    - publisher
                    type: object
                  maxItems: 1
                  type: array
                priority:
                  type: string
                privateIPAddress:
                  type: string
                privateIPAddresses:
                  items:
                    type: string
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                provisionVmAgent:
                  type: boolean
                proximityPlacementGroupID:
                  type: string
                publicIPAddress:
                  type: string
                publicIPAddresses:
                  items:
                    type: string
                  type: array
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                secret:
                  items:
                    properties:
                      certificate:
                        items:
                          properties:
                            store:
                              type: string
                            url:
                              type: string
                          required:
                          - store
                          - url
                          type: object
                        minItems: 1
                        type: array
                      keyVaultID:
                        type: string
                    required:
                    - certificate
                    - keyVaultID
                    type: object
                  type: array
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                size:
                  type: string
                sourceImageID:
                  type: string
                sourceImageReference:
                  items:
                    properties:
                      offer:
                        type: string
                      publisher:
                        type: string
                      sku:
                        type: string
                      version:
                        type: string
                    required:
                    - offer
                    - publisher
                    - sku
                    - version
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                timezone:
                  type: string
                virtualMachineID:
                  type: string
                virtualMachineScaleSetID:
                  type: string
                winrmListener:
                  items:
                    properties:
                      certificateURL:
                        type: string
                      protocol:
                        type: string
                    required:
                    - protocol
                    type: object
                  type: array
                zone:
                  type: string
              required:
              - adminUsername
              - location
              - name
              - networkInterfaceIDS
              - osDisk
              - providerRef
              - resourceGroupName
              - size
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
