apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: f4dpazsqls.modules.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: modules.kubeform.com
  names:
    kind: F4dpAzSql
    listKind: F4dpAzSqlList
    plural: f4dpazsqls
    singular: f4dpazsql
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalTags:
              additionalProperties:
                type: string
              description: Additional set of tags
              type: object
            commonTags:
              additionalProperties:
                type: string
              description: The tags to associate with assets
              type: object
            enableHA:
              description: If set to true, enable Failover Group
              type: boolean
            existingRg:
              description: if existing resource group need to be used
              type: boolean
            existingRgName:
              description: existing resource group name
              type: string
            locationPrimary:
              description: Location of primary server
              type: string
            locationSecondary:
              description: Location of primary server
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            rgName:
              description: Resource Group Name
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            source:
              type: string
            sqlAdminUsername:
              description: SQL Server username
              type: string
            sqlDbEdition:
              description: Edition of the SQL DB
              type: string
            sqlDbName:
              description: Name of the SQL DB
              type: string
            sqlDbRequestedServiceObjectiveName:
              description: Requested Service Objective Name of the SQL DB
              type: string
            sqlFwRules:
              additionalProperties:
                description: RawMessage is a raw encoded JSON value. It implements
                  Marshaler and Unmarshaler and can be used to delay JSON decoding
                  or precompute a JSON encoding.
                format: byte
                type: string
              description: "\t   Map of SQL Firewall Rules in the following format:
                \n \t     \"Name\" = [\"StartIP\", \"EndIP\"]"
              type: object
            sqlServerName:
              description: Name of the SQL Server
              type: string
          required:
          - providerRef
          - sqlAdminUsername
          - sqlDbName
          - sqlServerName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                sqlPassword:
                  type: string
              type: object
            phase:
              type: string
            state:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
