apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: sdpazadfv1s.modules.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: modules.kubeform.com
  names:
    kind: SDPAzadfv1
    listKind: SDPAzadfv1List
    plural: sdpazadfv1s
    singular: sdpazadfv1
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalTags:
              additionalProperties:
                type: string
              description: The tags to associate with your resource group.
              type: object
            environment:
              description: Environment. Upto 5 character. For e.g. dev, dev01 , prd01
              type: string
            githubConfiguration:
              description: List of Github Configuration
              items:
                properties:
                  accountName:
                    type: string
                  branchName:
                    type: string
                  gitURL:
                    type: string
                  repositoryName:
                    type: string
                  rootFolder:
                    type: string
                type: object
              type: array
            instance:
              description: Instance number
              type: string
            namePrefix:
              description: NamePrefix for the data factory
              type: string
            owner:
              description: owner
              type: string
            placement:
              description: placement
              type: string
            project:
              description: project stream name
              type: string
            projectStream:
              description: ' 4 character project stream name/code'
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              description: region. Choose from australia, europe, asia, europe
              type: string
            releaseVersion:
              description: releaseVersion
              type: string
            resourceGroupName:
              description: Resource Group name where the Data Factory needs to be
                created
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            source:
              type: string
            vstsConfiguration:
              description: List of VSTS Configuration
              items:
                properties:
                  accountName:
                    type: string
                  branchName:
                    type: string
                  projectName:
                    type: string
                  repositoryName:
                    type: string
                  rootFolder:
                    type: string
                  tenantID:
                    type: string
                type: object
              type: array
            workStream:
              description: ' 4 character project stream name/code'
              type: string
          required:
          - environment
          - namePrefix
          - owner
          - projectStream
          - providerRef
          - region
          - workStream
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                datafactoryID:
                  description: ID of the DataFactory
                  type: string
                datafactoryName:
                  description: Name of the DataFactory
                  type: string
                identity:
                  type: string
              type: object
            phase:
              type: string
            state:
              type: string
            terraformState:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
