/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/modules/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// SDPAzStgv1sGetter has a method to return a SDPAzStgv1Interface.
// A group's client should implement this interface.
type SDPAzStgv1sGetter interface {
	SDPAzStgv1s(namespace string) SDPAzStgv1Interface
}

// SDPAzStgv1Interface has methods to work with SDPAzStgv1 resources.
type SDPAzStgv1Interface interface {
	Create(*v1alpha1.SDPAzStgv1) (*v1alpha1.SDPAzStgv1, error)
	Update(*v1alpha1.SDPAzStgv1) (*v1alpha1.SDPAzStgv1, error)
	UpdateStatus(*v1alpha1.SDPAzStgv1) (*v1alpha1.SDPAzStgv1, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SDPAzStgv1, error)
	List(opts v1.ListOptions) (*v1alpha1.SDPAzStgv1List, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SDPAzStgv1, err error)
	SDPAzStgv1Expansion
}

// sDPAzStgv1s implements SDPAzStgv1Interface
type sDPAzStgv1s struct {
	client rest.Interface
	ns     string
}

// newSDPAzStgv1s returns a SDPAzStgv1s
func newSDPAzStgv1s(c *ModulesV1alpha1Client, namespace string) *sDPAzStgv1s {
	return &sDPAzStgv1s{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sDPAzStgv1, and returns the corresponding sDPAzStgv1 object, and an error if there is any.
func (c *sDPAzStgv1s) Get(name string, options v1.GetOptions) (result *v1alpha1.SDPAzStgv1, err error) {
	result = &v1alpha1.SDPAzStgv1{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SDPAzStgv1s that match those selectors.
func (c *sDPAzStgv1s) List(opts v1.ListOptions) (result *v1alpha1.SDPAzStgv1List, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SDPAzStgv1List{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sDPAzStgv1s.
func (c *sDPAzStgv1s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a sDPAzStgv1 and creates it.  Returns the server's representation of the sDPAzStgv1, and an error, if there is any.
func (c *sDPAzStgv1s) Create(sDPAzStgv1 *v1alpha1.SDPAzStgv1) (result *v1alpha1.SDPAzStgv1, err error) {
	result = &v1alpha1.SDPAzStgv1{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		Body(sDPAzStgv1).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sDPAzStgv1 and updates it. Returns the server's representation of the sDPAzStgv1, and an error, if there is any.
func (c *sDPAzStgv1s) Update(sDPAzStgv1 *v1alpha1.SDPAzStgv1) (result *v1alpha1.SDPAzStgv1, err error) {
	result = &v1alpha1.SDPAzStgv1{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		Name(sDPAzStgv1.Name).
		Body(sDPAzStgv1).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sDPAzStgv1s) UpdateStatus(sDPAzStgv1 *v1alpha1.SDPAzStgv1) (result *v1alpha1.SDPAzStgv1, err error) {
	result = &v1alpha1.SDPAzStgv1{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		Name(sDPAzStgv1.Name).
		SubResource("status").
		Body(sDPAzStgv1).
		Do().
		Into(result)
	return
}

// Delete takes name of the sDPAzStgv1 and deletes it. Returns an error if one occurs.
func (c *sDPAzStgv1s) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sDPAzStgv1s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sDPAzStgv1.
func (c *sDPAzStgv1s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SDPAzStgv1, err error) {
	result = &v1alpha1.SDPAzStgv1{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sdpazstgv1s").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
