/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
)

// BotChannelDirectlineLister helps list BotChannelDirectlines.
type BotChannelDirectlineLister interface {
	// List lists all BotChannelDirectlines in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.BotChannelDirectline, err error)
	// BotChannelDirectlines returns an object that can list and get BotChannelDirectlines.
	BotChannelDirectlines(namespace string) BotChannelDirectlineNamespaceLister
	BotChannelDirectlineListerExpansion
}

// botChannelDirectlineLister implements the BotChannelDirectlineLister interface.
type botChannelDirectlineLister struct {
	indexer cache.Indexer
}

// NewBotChannelDirectlineLister returns a new BotChannelDirectlineLister.
func NewBotChannelDirectlineLister(indexer cache.Indexer) BotChannelDirectlineLister {
	return &botChannelDirectlineLister{indexer: indexer}
}

// List lists all BotChannelDirectlines in the indexer.
func (s *botChannelDirectlineLister) List(selector labels.Selector) (ret []*v1alpha1.BotChannelDirectline, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BotChannelDirectline))
	})
	return ret, err
}

// BotChannelDirectlines returns an object that can list and get BotChannelDirectlines.
func (s *botChannelDirectlineLister) BotChannelDirectlines(namespace string) BotChannelDirectlineNamespaceLister {
	return botChannelDirectlineNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BotChannelDirectlineNamespaceLister helps list and get BotChannelDirectlines.
type BotChannelDirectlineNamespaceLister interface {
	// List lists all BotChannelDirectlines in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.BotChannelDirectline, err error)
	// Get retrieves the BotChannelDirectline from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.BotChannelDirectline, error)
	BotChannelDirectlineNamespaceListerExpansion
}

// botChannelDirectlineNamespaceLister implements the BotChannelDirectlineNamespaceLister
// interface.
type botChannelDirectlineNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BotChannelDirectlines in the indexer for a given namespace.
func (s botChannelDirectlineNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.BotChannelDirectline, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BotChannelDirectline))
	})
	return ret, err
}

// Get retrieves the BotChannelDirectline from the indexer for a given namespace and name.
func (s botChannelDirectlineNamespaceLister) Get(name string) (*v1alpha1.BotChannelDirectline, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("botchanneldirectline"), name)
	}
	return obj.(*v1alpha1.BotChannelDirectline), nil
}
