apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: sdpazplatformeventsv1s.modules.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: modules.kubeform.com
  names:
    kind: SDPAzplatformeventsv1
    listKind: SDPAzplatformeventsv1List
    plural: sdpazplatformeventsv1s
    singular: sdpazplatformeventsv1
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            environment:
              description: Environment. Upto 5 character. For e.g. dev, dev01 , prd01
              type: string
            instance:
              description: Instance number
              type: string
            owner:
              description: owner
              type: string
            placement:
              description: Public or Private placement
              type: string
            projectStream:
              description: ' 4 character project stream name/code'
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              description: region. Choose from australia, europe, asia, europe
              type: string
            releaseVersion:
              description: releaseVersion
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            source:
              type: string
            subscriptionRules:
              description: Subscription rules.
              format: byte
              type: string
            subscriptions:
              description: Subscription for the Topic in the namespace
              format: byte
              type: string
            workStream:
              description: ' 4 character project stream name/code'
              type: string
          required:
          - environment
          - projectStream
          - providerRef
          - workStream
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              type: object
            phase:
              type: string
            state:
              type: string
            terraformErrors:
              items:
                type: string
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
