apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: sdpazcosmosdbv1s.modules.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: modules.kubeform.com
  names:
    kind: SDPAzcosmosdbv1
    listKind: SDPAzcosmosdbv1List
    plural: sdpazcosmosdbv1s
    singular: sdpazcosmosdbv1
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalTags:
              additionalProperties:
                type: string
              description: Additional set of tags
              type: object
            allowedCidrs:
              description: 'CosmosDB Firewall Support: This value specifies the set
                of IP addresses or IP address ranges in CIDR form to be included as
                the allowed list of client IP''s for a given database account.'
              items:
                type: string
              type: array
            capabilities:
              description: "\t   Configures the capabilities to enable for this Cosmos
                DB account: \t   Possible values are \t     AllowSelfServeUpgradeToMongo36,
                DisableRateLimitingResponses, \t     EnableAggregationPipeline, EnableCassandra,
                EnableGremlin,EnableMongo, EnableTable, EnableServerless, \t     MongoDBv3.4
                and mongoEnableDocLevelTTL."
              items:
                type: string
              type: array
            consistencyPolicyLevel:
              description: Consistency policy level. Allowed values are `BoundedStaleness`,
                `Eventual`, `Session`, `Strong` or `ConsistentPrefix`
              type: string
            consistencyPolicyMaxIntervalInSeconds:
              description: When used with the Bounded Staleness consistency level,
                this value represents the time amount of staleness (in seconds) tolerated.
                Accepted range for this value is 5 - 86400 (1 day). Defaults to 5.
                Required when consistency_level is set to BoundedStaleness.
              type: string
            consistencyPolicyMaxStalenessPrefix:
              description: When used with the Bounded Staleness consistency level,
                this value represents the number of stale requests tolerated. Accepted
                range for this value is 10 – 2147483647. Defaults to 100. Required
                when consistency_level is set to BoundedStaleness.
              type: string
            databaseName:
              description: This is the name of the database to be created.
              type: string
            databaseThroughput:
              description: This is the throughput to be set at the database level.
                Optional. Throughput can be set at the database level, or at the object
                level inside the database.
              type: string
            environment:
              description: Environment. Upto 5 character. For e.g. dev, dev01 , prd01
              type: string
            existingResourceGroup:
              description: existing resource group name
              type: string
            instance:
              description: Instance number
              type: string
            isVirtualNetworkFilterEnabled:
              description: Enables virtual network filtering for this Cosmos DB account
              type: boolean
            kind:
              description: Specifies the Kind of CosmosDB to create - possible values
                are `GlobalDocumentDB` and `MongoDB`.
              type: string
            kvName:
              description: Azure Keyvault name to store Cosmos information
              type: string
            kvResourceGroupName:
              description: Azure Keyvault resource group name for Cosmos information
              type: string
            locations:
              additionalProperties:
                description: RawMessage is a raw encoded JSON value. It implements
                  Marshaler and Unmarshaler and can be used to delay JSON decoding
                  or precompute a JSON encoding.
                format: byte
                type: string
              description: The name of the Azure region to host replicated data and
                their priority.
              type: object
            namePrefix:
              description: Optional prefix for PostgreSQL server name
              type: string
            nameSuffix:
              description: Name suffix used for Cosmos account name and resource group
              type: string
            offerType:
              description: Specifies the Offer Type to use for this CosmosDB Account
                - currently this can only be set to Standard.
              type: string
            owner:
              description: owner
              type: string
            placement:
              description: placement
              type: string
            project:
              description: project stream name
              type: string
            projectStream:
              description: ' 4 character project stream name/code'
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              description: region. Choose from australia, europe, asia, europe
              type: string
            releaseVersion:
              description: releaseVersion
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            source:
              type: string
            virtualNetworkRule:
              description: Specifues a virtual_network_rules resource used to define
                which subnets are allowed to access this CosmosDB account
              items:
                properties:
                  ignoreMissingVnetServiceEndpoint:
                    type: boolean
                type: object
              type: array
            workStream:
              description: ' 4 character project stream name/code'
              type: string
          required:
          - databaseName
          - environment
          - owner
          - projectStream
          - providerRef
          - region
          - workStream
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                cosmosdbEndpoint:
                  description: The endpoint used to connect to the CosmosDB account.
                  type: string
                cosmosdbID:
                  description: The CosmosDB Account ID.
                  type: string
                cosmosdbName:
                  description: The CosmosDB Account Name.
                  type: string
                cosmosdbReadEndpoints:
                  description: A list of read endpoints available for this CosmosDB
                    account.
                  type: string
                cosmosdbWriteEndpoints:
                  description: A list of write endpoints available for this CosmosDB
                    account.
                  type: string
              type: object
            phase:
              type: string
            state:
              type: string
            terraformErrors:
              items:
                type: string
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
