apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: stratosazstgv1s.modules.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: modules.kubeform.com
  names:
    kind: StratosAzStgv1
    listKind: StratosAzStgv1List
    plural: stratosazstgv1s
    singular: stratosazstgv1
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            accountKind:
              description: Account Kind
              type: string
            accountTier:
              description: Account tier default is Standard
              type: string
            additionalTags:
              additionalProperties:
                type: string
              description: The tags to associate with assets
              type: object
            blobs:
              description: List of Blobs
              items:
                properties:
                  name:
                    type: string
                  type:
                    type: string
                type: object
              type: array
            containers:
              description: The name of the resource group in which to create the storage
                account. Changing this forces a new resource to be created.
              items:
                type: string
              type: array
            environment:
              description: Environment. Upto 5 character. For e.g. dev, dev01 , prd01
              type: string
            existingResourceGroup:
              description: The name of the resource group in which to create the storage
                account. Changing this forces a new resource to be created.
              type: string
            instance:
              description: Instance number
              type: string
            isHnsEnabled:
              type: boolean
            kvName:
              description: Azure Keyvault name to store SQL password
              type: string
            kvResourceGroupName:
              description: Azure Keyvault resource group name for SQL password
              type: string
            namePrefix:
              description: Specifies the name Prefix of storage account in which to
                create the storage container. Changing this forces a new resource
                to be created.
              type: string
            owner:
              description: owner
              type: string
            placement:
              description: placement
              type: string
            project:
              description: project stream name
              type: string
            projectStream:
              description: ' 4 character project stream name/code'
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            queues:
              description: List of Storage Queues
              items:
                type: string
              type: array
            region:
              description: region. Choose from australia, europe, asia, europe
              type: string
            releaseVersion:
              description: releaseVersion
              type: string
            replicationType:
              description: Sepcify replication type default is LRS
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            shares:
              description: List of Storage shares
              items:
                properties:
                  name:
                    type: string
                  quota:
                    description: A Number represents a JSON number literal.
                    type: string
                type: object
              type: array
            source:
              type: string
            tables:
              description: List of storage tables
              items:
                type: string
              type: array
            workStream:
              description: ' 4 character project stream name/code'
              type: string
          required:
          - environment
          - namePrefix
          - owner
          - projectStream
          - providerRef
          - region
          - workStream
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                storageAccountName:
                  type: string
              type: object
            phase:
              type: string
            state:
              type: string
            terraformErrors:
              items:
                type: string
              type: array
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
