/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// CustomProvidersGetter has a method to return a CustomProviderInterface.
// A group's client should implement this interface.
type CustomProvidersGetter interface {
	CustomProviders(namespace string) CustomProviderInterface
}

// CustomProviderInterface has methods to work with CustomProvider resources.
type CustomProviderInterface interface {
	Create(*v1alpha1.CustomProvider) (*v1alpha1.CustomProvider, error)
	Update(*v1alpha1.CustomProvider) (*v1alpha1.CustomProvider, error)
	UpdateStatus(*v1alpha1.CustomProvider) (*v1alpha1.CustomProvider, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CustomProvider, error)
	List(opts v1.ListOptions) (*v1alpha1.CustomProviderList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomProvider, err error)
	CustomProviderExpansion
}

// customProviders implements CustomProviderInterface
type customProviders struct {
	client rest.Interface
	ns     string
}

// newCustomProviders returns a CustomProviders
func newCustomProviders(c *AzurermV1alpha1Client, namespace string) *customProviders {
	return &customProviders{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the customProvider, and returns the corresponding customProvider object, and an error if there is any.
func (c *customProviders) Get(name string, options v1.GetOptions) (result *v1alpha1.CustomProvider, err error) {
	result = &v1alpha1.CustomProvider{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customproviders").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CustomProviders that match those selectors.
func (c *customProviders) List(opts v1.ListOptions) (result *v1alpha1.CustomProviderList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CustomProviderList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("customproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested customProviders.
func (c *customProviders) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("customproviders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a customProvider and creates it.  Returns the server's representation of the customProvider, and an error, if there is any.
func (c *customProviders) Create(customProvider *v1alpha1.CustomProvider) (result *v1alpha1.CustomProvider, err error) {
	result = &v1alpha1.CustomProvider{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("customproviders").
		Body(customProvider).
		Do().
		Into(result)
	return
}

// Update takes the representation of a customProvider and updates it. Returns the server's representation of the customProvider, and an error, if there is any.
func (c *customProviders) Update(customProvider *v1alpha1.CustomProvider) (result *v1alpha1.CustomProvider, err error) {
	result = &v1alpha1.CustomProvider{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("customproviders").
		Name(customProvider.Name).
		Body(customProvider).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *customProviders) UpdateStatus(customProvider *v1alpha1.CustomProvider) (result *v1alpha1.CustomProvider, err error) {
	result = &v1alpha1.CustomProvider{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("customproviders").
		Name(customProvider.Name).
		SubResource("status").
		Body(customProvider).
		Do().
		Into(result)
	return
}

// Delete takes name of the customProvider and deletes it. Returns an error if one occurs.
func (c *customProviders) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customproviders").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *customProviders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("customproviders").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched customProvider.
func (c *customProviders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomProvider, err error) {
	result = &v1alpha1.CustomProvider{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("customproviders").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
