/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// DatabaseMigrationServicesGetter has a method to return a DatabaseMigrationServiceInterface.
// A group's client should implement this interface.
type DatabaseMigrationServicesGetter interface {
	DatabaseMigrationServices(namespace string) DatabaseMigrationServiceInterface
}

// DatabaseMigrationServiceInterface has methods to work with DatabaseMigrationService resources.
type DatabaseMigrationServiceInterface interface {
	Create(*v1alpha1.DatabaseMigrationService) (*v1alpha1.DatabaseMigrationService, error)
	Update(*v1alpha1.DatabaseMigrationService) (*v1alpha1.DatabaseMigrationService, error)
	UpdateStatus(*v1alpha1.DatabaseMigrationService) (*v1alpha1.DatabaseMigrationService, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DatabaseMigrationService, error)
	List(opts v1.ListOptions) (*v1alpha1.DatabaseMigrationServiceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseMigrationService, err error)
	DatabaseMigrationServiceExpansion
}

// databaseMigrationServices implements DatabaseMigrationServiceInterface
type databaseMigrationServices struct {
	client rest.Interface
	ns     string
}

// newDatabaseMigrationServices returns a DatabaseMigrationServices
func newDatabaseMigrationServices(c *AzurermV1alpha1Client, namespace string) *databaseMigrationServices {
	return &databaseMigrationServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the databaseMigrationService, and returns the corresponding databaseMigrationService object, and an error if there is any.
func (c *databaseMigrationServices) Get(name string, options v1.GetOptions) (result *v1alpha1.DatabaseMigrationService, err error) {
	result = &v1alpha1.DatabaseMigrationService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databasemigrationservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DatabaseMigrationServices that match those selectors.
func (c *databaseMigrationServices) List(opts v1.ListOptions) (result *v1alpha1.DatabaseMigrationServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DatabaseMigrationServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("databasemigrationservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested databaseMigrationServices.
func (c *databaseMigrationServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("databasemigrationservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a databaseMigrationService and creates it.  Returns the server's representation of the databaseMigrationService, and an error, if there is any.
func (c *databaseMigrationServices) Create(databaseMigrationService *v1alpha1.DatabaseMigrationService) (result *v1alpha1.DatabaseMigrationService, err error) {
	result = &v1alpha1.DatabaseMigrationService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("databasemigrationservices").
		Body(databaseMigrationService).
		Do().
		Into(result)
	return
}

// Update takes the representation of a databaseMigrationService and updates it. Returns the server's representation of the databaseMigrationService, and an error, if there is any.
func (c *databaseMigrationServices) Update(databaseMigrationService *v1alpha1.DatabaseMigrationService) (result *v1alpha1.DatabaseMigrationService, err error) {
	result = &v1alpha1.DatabaseMigrationService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databasemigrationservices").
		Name(databaseMigrationService.Name).
		Body(databaseMigrationService).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *databaseMigrationServices) UpdateStatus(databaseMigrationService *v1alpha1.DatabaseMigrationService) (result *v1alpha1.DatabaseMigrationService, err error) {
	result = &v1alpha1.DatabaseMigrationService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("databasemigrationservices").
		Name(databaseMigrationService.Name).
		SubResource("status").
		Body(databaseMigrationService).
		Do().
		Into(result)
	return
}

// Delete takes name of the databaseMigrationService and deletes it. Returns an error if one occurs.
func (c *databaseMigrationServices) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databasemigrationservices").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *databaseMigrationServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("databasemigrationservices").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched databaseMigrationService.
func (c *databaseMigrationServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DatabaseMigrationService, err error) {
	result = &v1alpha1.DatabaseMigrationService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("databasemigrationservices").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
