/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// EventgridDomainTopicsGetter has a method to return a EventgridDomainTopicInterface.
// A group's client should implement this interface.
type EventgridDomainTopicsGetter interface {
	EventgridDomainTopics(namespace string) EventgridDomainTopicInterface
}

// EventgridDomainTopicInterface has methods to work with EventgridDomainTopic resources.
type EventgridDomainTopicInterface interface {
	Create(*v1alpha1.EventgridDomainTopic) (*v1alpha1.EventgridDomainTopic, error)
	Update(*v1alpha1.EventgridDomainTopic) (*v1alpha1.EventgridDomainTopic, error)
	UpdateStatus(*v1alpha1.EventgridDomainTopic) (*v1alpha1.EventgridDomainTopic, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.EventgridDomainTopic, error)
	List(opts v1.ListOptions) (*v1alpha1.EventgridDomainTopicList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EventgridDomainTopic, err error)
	EventgridDomainTopicExpansion
}

// eventgridDomainTopics implements EventgridDomainTopicInterface
type eventgridDomainTopics struct {
	client rest.Interface
	ns     string
}

// newEventgridDomainTopics returns a EventgridDomainTopics
func newEventgridDomainTopics(c *AzurermV1alpha1Client, namespace string) *eventgridDomainTopics {
	return &eventgridDomainTopics{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the eventgridDomainTopic, and returns the corresponding eventgridDomainTopic object, and an error if there is any.
func (c *eventgridDomainTopics) Get(name string, options v1.GetOptions) (result *v1alpha1.EventgridDomainTopic, err error) {
	result = &v1alpha1.EventgridDomainTopic{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EventgridDomainTopics that match those selectors.
func (c *eventgridDomainTopics) List(opts v1.ListOptions) (result *v1alpha1.EventgridDomainTopicList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.EventgridDomainTopicList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested eventgridDomainTopics.
func (c *eventgridDomainTopics) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a eventgridDomainTopic and creates it.  Returns the server's representation of the eventgridDomainTopic, and an error, if there is any.
func (c *eventgridDomainTopics) Create(eventgridDomainTopic *v1alpha1.EventgridDomainTopic) (result *v1alpha1.EventgridDomainTopic, err error) {
	result = &v1alpha1.EventgridDomainTopic{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		Body(eventgridDomainTopic).
		Do().
		Into(result)
	return
}

// Update takes the representation of a eventgridDomainTopic and updates it. Returns the server's representation of the eventgridDomainTopic, and an error, if there is any.
func (c *eventgridDomainTopics) Update(eventgridDomainTopic *v1alpha1.EventgridDomainTopic) (result *v1alpha1.EventgridDomainTopic, err error) {
	result = &v1alpha1.EventgridDomainTopic{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		Name(eventgridDomainTopic.Name).
		Body(eventgridDomainTopic).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *eventgridDomainTopics) UpdateStatus(eventgridDomainTopic *v1alpha1.EventgridDomainTopic) (result *v1alpha1.EventgridDomainTopic, err error) {
	result = &v1alpha1.EventgridDomainTopic{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		Name(eventgridDomainTopic.Name).
		SubResource("status").
		Body(eventgridDomainTopic).
		Do().
		Into(result)
	return
}

// Delete takes name of the eventgridDomainTopic and deletes it. Returns an error if one occurs.
func (c *eventgridDomainTopics) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *eventgridDomainTopics) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched eventgridDomainTopic.
func (c *eventgridDomainTopics) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EventgridDomainTopic, err error) {
	result = &v1alpha1.EventgridDomainTopic{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("eventgriddomaintopics").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
