/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// IotTimeSeriesInsightsReferenceDataSetsGetter has a method to return a IotTimeSeriesInsightsReferenceDataSetInterface.
// A group's client should implement this interface.
type IotTimeSeriesInsightsReferenceDataSetsGetter interface {
	IotTimeSeriesInsightsReferenceDataSets(namespace string) IotTimeSeriesInsightsReferenceDataSetInterface
}

// IotTimeSeriesInsightsReferenceDataSetInterface has methods to work with IotTimeSeriesInsightsReferenceDataSet resources.
type IotTimeSeriesInsightsReferenceDataSetInterface interface {
	Create(*v1alpha1.IotTimeSeriesInsightsReferenceDataSet) (*v1alpha1.IotTimeSeriesInsightsReferenceDataSet, error)
	Update(*v1alpha1.IotTimeSeriesInsightsReferenceDataSet) (*v1alpha1.IotTimeSeriesInsightsReferenceDataSet, error)
	UpdateStatus(*v1alpha1.IotTimeSeriesInsightsReferenceDataSet) (*v1alpha1.IotTimeSeriesInsightsReferenceDataSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.IotTimeSeriesInsightsReferenceDataSet, error)
	List(opts v1.ListOptions) (*v1alpha1.IotTimeSeriesInsightsReferenceDataSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IotTimeSeriesInsightsReferenceDataSet, err error)
	IotTimeSeriesInsightsReferenceDataSetExpansion
}

// iotTimeSeriesInsightsReferenceDataSets implements IotTimeSeriesInsightsReferenceDataSetInterface
type iotTimeSeriesInsightsReferenceDataSets struct {
	client rest.Interface
	ns     string
}

// newIotTimeSeriesInsightsReferenceDataSets returns a IotTimeSeriesInsightsReferenceDataSets
func newIotTimeSeriesInsightsReferenceDataSets(c *AzurermV1alpha1Client, namespace string) *iotTimeSeriesInsightsReferenceDataSets {
	return &iotTimeSeriesInsightsReferenceDataSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the iotTimeSeriesInsightsReferenceDataSet, and returns the corresponding iotTimeSeriesInsightsReferenceDataSet object, and an error if there is any.
func (c *iotTimeSeriesInsightsReferenceDataSets) Get(name string, options v1.GetOptions) (result *v1alpha1.IotTimeSeriesInsightsReferenceDataSet, err error) {
	result = &v1alpha1.IotTimeSeriesInsightsReferenceDataSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of IotTimeSeriesInsightsReferenceDataSets that match those selectors.
func (c *iotTimeSeriesInsightsReferenceDataSets) List(opts v1.ListOptions) (result *v1alpha1.IotTimeSeriesInsightsReferenceDataSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.IotTimeSeriesInsightsReferenceDataSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested iotTimeSeriesInsightsReferenceDataSets.
func (c *iotTimeSeriesInsightsReferenceDataSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a iotTimeSeriesInsightsReferenceDataSet and creates it.  Returns the server's representation of the iotTimeSeriesInsightsReferenceDataSet, and an error, if there is any.
func (c *iotTimeSeriesInsightsReferenceDataSets) Create(iotTimeSeriesInsightsReferenceDataSet *v1alpha1.IotTimeSeriesInsightsReferenceDataSet) (result *v1alpha1.IotTimeSeriesInsightsReferenceDataSet, err error) {
	result = &v1alpha1.IotTimeSeriesInsightsReferenceDataSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		Body(iotTimeSeriesInsightsReferenceDataSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a iotTimeSeriesInsightsReferenceDataSet and updates it. Returns the server's representation of the iotTimeSeriesInsightsReferenceDataSet, and an error, if there is any.
func (c *iotTimeSeriesInsightsReferenceDataSets) Update(iotTimeSeriesInsightsReferenceDataSet *v1alpha1.IotTimeSeriesInsightsReferenceDataSet) (result *v1alpha1.IotTimeSeriesInsightsReferenceDataSet, err error) {
	result = &v1alpha1.IotTimeSeriesInsightsReferenceDataSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		Name(iotTimeSeriesInsightsReferenceDataSet.Name).
		Body(iotTimeSeriesInsightsReferenceDataSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *iotTimeSeriesInsightsReferenceDataSets) UpdateStatus(iotTimeSeriesInsightsReferenceDataSet *v1alpha1.IotTimeSeriesInsightsReferenceDataSet) (result *v1alpha1.IotTimeSeriesInsightsReferenceDataSet, err error) {
	result = &v1alpha1.IotTimeSeriesInsightsReferenceDataSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		Name(iotTimeSeriesInsightsReferenceDataSet.Name).
		SubResource("status").
		Body(iotTimeSeriesInsightsReferenceDataSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the iotTimeSeriesInsightsReferenceDataSet and deletes it. Returns an error if one occurs.
func (c *iotTimeSeriesInsightsReferenceDataSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *iotTimeSeriesInsightsReferenceDataSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched iotTimeSeriesInsightsReferenceDataSet.
func (c *iotTimeSeriesInsightsReferenceDataSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.IotTimeSeriesInsightsReferenceDataSet, err error) {
	result = &v1alpha1.IotTimeSeriesInsightsReferenceDataSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("iottimeseriesinsightsreferencedatasets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
