/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// ManagedApplicationsGetter has a method to return a ManagedApplicationInterface.
// A group's client should implement this interface.
type ManagedApplicationsGetter interface {
	ManagedApplications(namespace string) ManagedApplicationInterface
}

// ManagedApplicationInterface has methods to work with ManagedApplication resources.
type ManagedApplicationInterface interface {
	Create(*v1alpha1.ManagedApplication) (*v1alpha1.ManagedApplication, error)
	Update(*v1alpha1.ManagedApplication) (*v1alpha1.ManagedApplication, error)
	UpdateStatus(*v1alpha1.ManagedApplication) (*v1alpha1.ManagedApplication, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ManagedApplication, error)
	List(opts v1.ListOptions) (*v1alpha1.ManagedApplicationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ManagedApplication, err error)
	ManagedApplicationExpansion
}

// managedApplications implements ManagedApplicationInterface
type managedApplications struct {
	client rest.Interface
	ns     string
}

// newManagedApplications returns a ManagedApplications
func newManagedApplications(c *AzurermV1alpha1Client, namespace string) *managedApplications {
	return &managedApplications{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the managedApplication, and returns the corresponding managedApplication object, and an error if there is any.
func (c *managedApplications) Get(name string, options v1.GetOptions) (result *v1alpha1.ManagedApplication, err error) {
	result = &v1alpha1.ManagedApplication{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedapplications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManagedApplications that match those selectors.
func (c *managedApplications) List(opts v1.ListOptions) (result *v1alpha1.ManagedApplicationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ManagedApplicationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managedapplications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested managedApplications.
func (c *managedApplications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("managedapplications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a managedApplication and creates it.  Returns the server's representation of the managedApplication, and an error, if there is any.
func (c *managedApplications) Create(managedApplication *v1alpha1.ManagedApplication) (result *v1alpha1.ManagedApplication, err error) {
	result = &v1alpha1.ManagedApplication{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("managedapplications").
		Body(managedApplication).
		Do().
		Into(result)
	return
}

// Update takes the representation of a managedApplication and updates it. Returns the server's representation of the managedApplication, and an error, if there is any.
func (c *managedApplications) Update(managedApplication *v1alpha1.ManagedApplication) (result *v1alpha1.ManagedApplication, err error) {
	result = &v1alpha1.ManagedApplication{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedapplications").
		Name(managedApplication.Name).
		Body(managedApplication).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *managedApplications) UpdateStatus(managedApplication *v1alpha1.ManagedApplication) (result *v1alpha1.ManagedApplication, err error) {
	result = &v1alpha1.ManagedApplication{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managedapplications").
		Name(managedApplication.Name).
		SubResource("status").
		Body(managedApplication).
		Do().
		Into(result)
	return
}

// Delete takes name of the managedApplication and deletes it. Returns an error if one occurs.
func (c *managedApplications) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedapplications").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *managedApplications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managedapplications").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched managedApplication.
func (c *managedApplications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ManagedApplication, err error) {
	result = &v1alpha1.ManagedApplication{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("managedapplications").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
