/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// MssqlVirtualMachinesGetter has a method to return a MssqlVirtualMachineInterface.
// A group's client should implement this interface.
type MssqlVirtualMachinesGetter interface {
	MssqlVirtualMachines(namespace string) MssqlVirtualMachineInterface
}

// MssqlVirtualMachineInterface has methods to work with MssqlVirtualMachine resources.
type MssqlVirtualMachineInterface interface {
	Create(*v1alpha1.MssqlVirtualMachine) (*v1alpha1.MssqlVirtualMachine, error)
	Update(*v1alpha1.MssqlVirtualMachine) (*v1alpha1.MssqlVirtualMachine, error)
	UpdateStatus(*v1alpha1.MssqlVirtualMachine) (*v1alpha1.MssqlVirtualMachine, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MssqlVirtualMachine, error)
	List(opts v1.ListOptions) (*v1alpha1.MssqlVirtualMachineList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MssqlVirtualMachine, err error)
	MssqlVirtualMachineExpansion
}

// mssqlVirtualMachines implements MssqlVirtualMachineInterface
type mssqlVirtualMachines struct {
	client rest.Interface
	ns     string
}

// newMssqlVirtualMachines returns a MssqlVirtualMachines
func newMssqlVirtualMachines(c *AzurermV1alpha1Client, namespace string) *mssqlVirtualMachines {
	return &mssqlVirtualMachines{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mssqlVirtualMachine, and returns the corresponding mssqlVirtualMachine object, and an error if there is any.
func (c *mssqlVirtualMachines) Get(name string, options v1.GetOptions) (result *v1alpha1.MssqlVirtualMachine, err error) {
	result = &v1alpha1.MssqlVirtualMachine{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MssqlVirtualMachines that match those selectors.
func (c *mssqlVirtualMachines) List(opts v1.ListOptions) (result *v1alpha1.MssqlVirtualMachineList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MssqlVirtualMachineList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mssqlVirtualMachines.
func (c *mssqlVirtualMachines) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a mssqlVirtualMachine and creates it.  Returns the server's representation of the mssqlVirtualMachine, and an error, if there is any.
func (c *mssqlVirtualMachines) Create(mssqlVirtualMachine *v1alpha1.MssqlVirtualMachine) (result *v1alpha1.MssqlVirtualMachine, err error) {
	result = &v1alpha1.MssqlVirtualMachine{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		Body(mssqlVirtualMachine).
		Do().
		Into(result)
	return
}

// Update takes the representation of a mssqlVirtualMachine and updates it. Returns the server's representation of the mssqlVirtualMachine, and an error, if there is any.
func (c *mssqlVirtualMachines) Update(mssqlVirtualMachine *v1alpha1.MssqlVirtualMachine) (result *v1alpha1.MssqlVirtualMachine, err error) {
	result = &v1alpha1.MssqlVirtualMachine{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		Name(mssqlVirtualMachine.Name).
		Body(mssqlVirtualMachine).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *mssqlVirtualMachines) UpdateStatus(mssqlVirtualMachine *v1alpha1.MssqlVirtualMachine) (result *v1alpha1.MssqlVirtualMachine, err error) {
	result = &v1alpha1.MssqlVirtualMachine{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		Name(mssqlVirtualMachine.Name).
		SubResource("status").
		Body(mssqlVirtualMachine).
		Do().
		Into(result)
	return
}

// Delete takes name of the mssqlVirtualMachine and deletes it. Returns an error if one occurs.
func (c *mssqlVirtualMachines) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mssqlVirtualMachines) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched mssqlVirtualMachine.
func (c *mssqlVirtualMachines) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MssqlVirtualMachine, err error) {
	result = &v1alpha1.MssqlVirtualMachine{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mssqlvirtualmachines").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
