/*
Copyright The Kubeform Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubeform.dev/kubeform/apis/azurerm/v1alpha1"
	scheme "kubeform.dev/kubeform/client/clientset/versioned/scheme"
)

// ServicebusNamespaceNetworkRuleSetsGetter has a method to return a ServicebusNamespaceNetworkRuleSetInterface.
// A group's client should implement this interface.
type ServicebusNamespaceNetworkRuleSetsGetter interface {
	ServicebusNamespaceNetworkRuleSets(namespace string) ServicebusNamespaceNetworkRuleSetInterface
}

// ServicebusNamespaceNetworkRuleSetInterface has methods to work with ServicebusNamespaceNetworkRuleSet resources.
type ServicebusNamespaceNetworkRuleSetInterface interface {
	Create(*v1alpha1.ServicebusNamespaceNetworkRuleSet) (*v1alpha1.ServicebusNamespaceNetworkRuleSet, error)
	Update(*v1alpha1.ServicebusNamespaceNetworkRuleSet) (*v1alpha1.ServicebusNamespaceNetworkRuleSet, error)
	UpdateStatus(*v1alpha1.ServicebusNamespaceNetworkRuleSet) (*v1alpha1.ServicebusNamespaceNetworkRuleSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ServicebusNamespaceNetworkRuleSet, error)
	List(opts v1.ListOptions) (*v1alpha1.ServicebusNamespaceNetworkRuleSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServicebusNamespaceNetworkRuleSet, err error)
	ServicebusNamespaceNetworkRuleSetExpansion
}

// servicebusNamespaceNetworkRuleSets implements ServicebusNamespaceNetworkRuleSetInterface
type servicebusNamespaceNetworkRuleSets struct {
	client rest.Interface
	ns     string
}

// newServicebusNamespaceNetworkRuleSets returns a ServicebusNamespaceNetworkRuleSets
func newServicebusNamespaceNetworkRuleSets(c *AzurermV1alpha1Client, namespace string) *servicebusNamespaceNetworkRuleSets {
	return &servicebusNamespaceNetworkRuleSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the servicebusNamespaceNetworkRuleSet, and returns the corresponding servicebusNamespaceNetworkRuleSet object, and an error if there is any.
func (c *servicebusNamespaceNetworkRuleSets) Get(name string, options v1.GetOptions) (result *v1alpha1.ServicebusNamespaceNetworkRuleSet, err error) {
	result = &v1alpha1.ServicebusNamespaceNetworkRuleSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServicebusNamespaceNetworkRuleSets that match those selectors.
func (c *servicebusNamespaceNetworkRuleSets) List(opts v1.ListOptions) (result *v1alpha1.ServicebusNamespaceNetworkRuleSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ServicebusNamespaceNetworkRuleSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested servicebusNamespaceNetworkRuleSets.
func (c *servicebusNamespaceNetworkRuleSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a servicebusNamespaceNetworkRuleSet and creates it.  Returns the server's representation of the servicebusNamespaceNetworkRuleSet, and an error, if there is any.
func (c *servicebusNamespaceNetworkRuleSets) Create(servicebusNamespaceNetworkRuleSet *v1alpha1.ServicebusNamespaceNetworkRuleSet) (result *v1alpha1.ServicebusNamespaceNetworkRuleSet, err error) {
	result = &v1alpha1.ServicebusNamespaceNetworkRuleSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		Body(servicebusNamespaceNetworkRuleSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a servicebusNamespaceNetworkRuleSet and updates it. Returns the server's representation of the servicebusNamespaceNetworkRuleSet, and an error, if there is any.
func (c *servicebusNamespaceNetworkRuleSets) Update(servicebusNamespaceNetworkRuleSet *v1alpha1.ServicebusNamespaceNetworkRuleSet) (result *v1alpha1.ServicebusNamespaceNetworkRuleSet, err error) {
	result = &v1alpha1.ServicebusNamespaceNetworkRuleSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		Name(servicebusNamespaceNetworkRuleSet.Name).
		Body(servicebusNamespaceNetworkRuleSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *servicebusNamespaceNetworkRuleSets) UpdateStatus(servicebusNamespaceNetworkRuleSet *v1alpha1.ServicebusNamespaceNetworkRuleSet) (result *v1alpha1.ServicebusNamespaceNetworkRuleSet, err error) {
	result = &v1alpha1.ServicebusNamespaceNetworkRuleSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		Name(servicebusNamespaceNetworkRuleSet.Name).
		SubResource("status").
		Body(servicebusNamespaceNetworkRuleSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the servicebusNamespaceNetworkRuleSet and deletes it. Returns an error if one occurs.
func (c *servicebusNamespaceNetworkRuleSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *servicebusNamespaceNetworkRuleSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched servicebusNamespaceNetworkRuleSet.
func (c *servicebusNamespaceNetworkRuleSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ServicebusNamespaceNetworkRuleSet, err error) {
	result = &v1alpha1.ServicebusNamespaceNetworkRuleSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("servicebusnamespacenetworkrulesets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
